/**
 * Hebrew city / locality name → translations.
 * Major cities have full ru/ar/fr translations.
 * Smaller localities have at minimum an `en` entry so the UI never
 * falls back to Hebrew for non-Hebrew speakers.
 *
 * Fallback order in translateCity():  lang → en → Hebrew original
 */
export const CITY_TRANSLATIONS: Record<string, Record<string, string>> = {

  // ── Major cities (full translations) ────────────────────────────────────────
  'תל אביב יפו':        { en: 'Tel Aviv-Yafo',         ru: 'Тель-Авив-Яффо',    ar: 'تل أبيب-يافا',        fr: 'Tel Aviv-Jaffa' },
  'תל אביב - יפו':      { en: 'Tel Aviv-Yafo',         ru: 'Тель-Авив-Яффо',    ar: 'تل أبيب-يافا',        fr: 'Tel Aviv-Jaffa' },
  'ירושלים':            { en: 'Jerusalem',              ru: 'Иерусалим',         ar: 'القدس',               fr: 'Jérusalem' },
  'חיפה':               { en: 'Haifa',                  ru: 'Хайфа',             ar: 'حيفا',                fr: 'Haïfa' },
  'ראשון לציון':        { en: 'Rishon LeZion',          ru: 'Ришон-ле-Цион',     ar: 'ريشون لتسيون',        fr: 'Rishon LeZion' },
  'פתח תקווה':          { en: 'Petah Tikva',            ru: 'Петах-Тиква',       ar: 'بيتاح تكفا',          fr: 'Petah Tikva' },
  'אשדוד':              { en: 'Ashdod',                 ru: 'Ашдод',             ar: 'أشدود',               fr: 'Ashdod' },
  'נתניה':              { en: 'Netanya',                ru: 'Нетания',           ar: 'نتانيا',              fr: 'Netanya' },
  'באר שבע':            { en: "Be'er Sheva",            ru: 'Беэр-Шева',         ar: 'بئر السبع',           fr: 'Beer-Sheva' },
  'בני ברק':            { en: 'Bnei Brak',              ru: 'Бней-Брак',         ar: 'بني براك',            fr: 'Bnei Brak' },
  'חולון':              { en: 'Holon',                  ru: 'Холон',             ar: 'حولون',               fr: 'Holon' },
  'רמת גן':             { en: 'Ramat Gan',              ru: 'Рамат-Ган',         ar: 'رمات غان',            fr: 'Ramat Gan' },
  'אשקלון':             { en: 'Ashkelon',               ru: 'Ашкелон',           ar: 'عسقلان',              fr: 'Ashkelon' },
  'רחובות':             { en: 'Rehovot',                ru: 'Реховот',           ar: 'رحوفوت',              fr: 'Rehovot' },
  'בת ים':              { en: 'Bat Yam',                ru: 'Бат-Ям',            ar: 'بات يام',             fr: 'Bat Yam' },
  'הרצליה':             { en: 'Herzliya',               ru: 'Герцлия',           ar: 'هرتسليا',             fr: 'Herzliya' },
  'כפר סבא':            { en: 'Kfar Saba',              ru: 'Кфар-Сава',         ar: 'كفار سابا',           fr: 'Kfar Saba' },
  'מודיעין מכבים רעות': { en: "Modi'in",                ru: 'Модиин',            ar: 'موديعين',             fr: "Modi'in" },
  'מודיעין-מכבים-רעות': { en: "Modi'in",                ru: 'Модиин',            ar: 'موديعين',             fr: "Modi'in" },
  'רעננה':              { en: "Ra'anana",               ru: 'Раанана',           ar: 'رعنانا',              fr: "Ra'anana" },
  'לוד':                { en: 'Lod',                    ru: 'Лод',               ar: 'اللد',                fr: 'Lod' },
  'רמלה':               { en: 'Ramla',                  ru: 'Рамла',             ar: 'الرملة',              fr: 'Ramla' },
  'נס ציונה':           { en: 'Nes Ziona',              ru: 'Нес-Циона',         ar: 'نس تسيونا',           fr: 'Nes Ziona' },
  'יבנה':               { en: 'Yavne',                  ru: 'Явне',              ar: 'يبنه',                fr: 'Yavne' },
  'גבעתיים':            { en: 'Givatayim',              ru: 'Гиватаим',          ar: 'غيفعتايم',            fr: 'Givatayim' },
  'הוד השרון':          { en: 'Hod HaSharon',           ru: 'Ход-ха-Шарон',      ar: 'هود هشارون',          fr: 'Hod HaSharon' },
  'גבעת שמואל':         { en: 'Givat Shmuel',           ru: 'Гиват-Шмуэль',      ar: 'غيفعات شموئيל',       fr: 'Givat Shmuel' },
  'קריית גת':           { en: 'Kiryat Gat',             ru: 'Кирьят-Гат',        ar: 'كريات جات',           fr: 'Kiryat Gat' },
  'עכו':                { en: 'Acre',                   ru: 'Акко',              ar: 'عكا',                 fr: 'Acre' },
  'נהריה':              { en: 'Nahariya',               ru: 'Нагария',           ar: 'نهاريا',              fr: 'Nahariya' },
  'כרמיאל':             { en: 'Karmiel',                ru: 'Кармиэль',          ar: 'كرميئيل',             fr: 'Karmiel' },
  'אילת':               { en: 'Eilat',                  ru: 'Эйлат',             ar: 'إيلات',               fr: 'Eilat' },
  'אריאל':              { en: 'Ariel',                  ru: 'Ариэль',            ar: 'أريئيل',              fr: 'Ariel' },
  'בית שמש':            { en: 'Beit Shemesh',           ru: 'Бейт-Шемеш',        ar: 'بيت شيمش',            fr: 'Beit Shemesh' },
  'מעלה אדומים':        { en: "Ma'ale Adumim",          ru: 'Маале-Адумим',      ar: 'معاليه أدوميم',       fr: "Ma'ale Adumim" },
  'אור יהודה':          { en: 'Or Yehuda',              ru: 'Ор-Иегуда',         ar: 'أور يهودا',           fr: 'Or Yehuda' },
  'באר יעקב':           { en: "Be'er Ya'akov",          ru: 'Беэр-Яаков',        ar: 'بئر يعقوب',           fr: "Be'er Ya'akov" },
  'אופקים':             { en: 'Ofakim',                 ru: 'Офаким',            ar: 'أوفاكيم',             fr: 'Ofakim' },
  'בית אל':             { en: 'Beit El',                ru: 'Бейт-Эль',          ar: 'بيت إيل',             fr: 'Beit El' },
  'חריש':               { en: 'Harish',                 ru: 'Хариш',             ar: 'حريش',                fr: 'Harish' },
  'עפולה':              { en: 'Afula',                  ru: 'Афула',             ar: 'العفولة',             fr: 'Afula' },
  'נצרת':               { en: 'Nazareth',               ru: 'Назарет',           ar: 'الناصرة',             fr: 'Nazareth' },
  'נוף הגליל':          { en: 'Nof HaGalil',            ru: 'Ноф-ха-Галиль',     ar: 'نوف هجليل',           fr: 'Nof HaGalil' },
  'נצרת עילית':         { en: 'Nof HaGalil',            ru: 'Ноф-ха-Галиль',     ar: 'نوف هجليل',           fr: 'Nof HaGalil' },
  'בית שאן':            { en: "Beit She'an",            ru: 'Бейт-Шеан',         ar: 'بيت شيان',            fr: "Beit She'an" },
  'מעלות-תרשיחא':      { en: "Ma'alot-Tarshiha",       ru: 'Маалот-Таршиха',    ar: 'معلوت-ترشيحا',        fr: "Ma'alot-Tarshiha" },
  'מגדל העמק':          { en: 'Migdal HaEmek',          ru: 'Мигдаль-ха-Эмек',   ar: 'مجدل هاعيمك',         fr: 'Migdal HaEmek' },
  'קריית שמונה':        { en: 'Kiryat Shmona',          ru: 'Кирьят-Шмона',      ar: 'كريات شمونه',         fr: 'Kiryat Shmona' },
  'קרית שמונה':         { en: 'Kiryat Shmona',          ru: 'Кирьят-Шмона',      ar: 'كريات شمونه',         fr: 'Kiryat Shmona' },
  'צפת':                { en: 'Safed',                  ru: 'Цфат',              ar: 'صفد',                 fr: 'Safed' },
  'טבריה':              { en: 'Tiberias',               ru: 'Тверия',            ar: 'طبريا',               fr: 'Tibériade' },
  'דימונה':             { en: 'Dimona',                 ru: 'Димона',            ar: 'ديمونا',              fr: 'Dimona' },
  'ערד':                { en: 'Arad',                   ru: 'Арад',              ar: 'عراد',                fr: 'Arad' },
  'מצפה רמון':          { en: 'Mitzpe Ramon',           ru: 'Мицпе-Рамон',       ar: 'ميتسبي رامون',        fr: 'Mitzpe Ramon' },
  'נתיבות':             { en: 'Netivot',                ru: 'Нетивот',           ar: 'نتيفوت',              fr: 'Netivot' },
  'שדרות':              { en: 'Sderot',                 ru: 'Сдерот',            ar: 'سديروت',              fr: 'Sderot' },
  'קריית מלאכי':        { en: 'Kiryat Malakhi',         ru: 'Кирьят-Малахи',     ar: 'كريات ملآخي',         fr: 'Kiryat Malakhi' },
  'קרית מלאכי':         { en: 'Kiryat Malakhi',         ru: 'Кирьят-Малахи',     ar: 'كريات ملآخي',         fr: 'Kiryat Malakhi' },
  'רהט':                { en: 'Rahat',                  ru: 'Рахат',             ar: 'رهط',                 fr: 'Rahat' },
  'תל שבע':             { en: 'Tel Sheva',              ru: 'Тель-Шева',         ar: 'تل السبع',            fr: 'Tel Sheva' },
  'לקיה':               { en: 'Lakiya',                 ru: 'Лакия',             ar: 'لقية',                fr: 'Lakiya' },
  'חורה':               { en: 'Hura',                   ru: 'Хура',              ar: 'حورة',                fr: 'Hura' },
  'כסיפה':              { en: 'Kseife',                 ru: 'Ксейфе',            ar: 'كسيفة',               fr: 'Kseife' },
  'ערערה-בנגב':         { en: "Ar'ara BaNegev",         ru: 'Арара-ба-Негев',    ar: 'عرعرة النقب',         fr: "Ar'ara BaNegev" },
  'שגב-שלום':           { en: 'Segev-Shalom',           ru: 'Сегев-Шалом',       ar: 'سيغف شالوم',          fr: 'Segev-Shalom' },
  'אום אל-פחם':         { en: 'Umm al-Fahm',            ru: 'Умм-эль-Фахм',      ar: 'أم الفحم',            fr: 'Umm al-Fahm' },
  'אום אל פחם':         { en: 'Umm al-Fahm',            ru: 'Умм-эль-Фахм',      ar: 'أم الفحم',            fr: 'Umm al-Fahm' },
  'טייבה':              { en: 'Tayibe',                 ru: 'Тайбе',             ar: 'الطيبة',              fr: 'Tayibe' },
  'קלנסוואה':           { en: 'Qalansuwa',              ru: 'Каланусуа',         ar: 'قلنسوة',              fr: 'Qalansuwa' },
  'קלנסווה':            { en: 'Qalansuwa',              ru: 'Каланусуа',         ar: 'قلنسوة',              fr: 'Qalansuwa' },
  'כפר קאסם':           { en: 'Kafr Qasim',             ru: 'Кафр-Касем',        ar: 'كفر قاسم',            fr: 'Kafr Qasim' },
  'טירה':               { en: 'Tire',                   ru: 'Тира',              ar: 'الطيرة',              fr: 'Tire' },
  "ג'לג'וליה":          { en: 'Jaljulia',               ru: 'Джалджулия',        ar: 'جلجولية',             fr: 'Jaljulia' },
  'באקה אל-גרביה':      { en: 'Baka al-Gharbiyye',      ru: 'Бака-эль-Гарбие',   ar: 'باقة الغربية',        fr: 'Baka al-Gharbiyye' },
  "ג'סר א-זרקא":        { en: 'Jisr az-Zarqa',          ru: 'Джиср-эз-Зарка',    ar: 'جسر الزرقاء',         fr: 'Jisr az-Zarqa' },
  'כפר קרע':            { en: 'Kafr Qara',              ru: 'Кафр-Кара',         ar: 'كفر قرع',             fr: 'Kafr Qara' },
  'ערערה':              { en: "Ar'ara",                 ru: 'Арара',             ar: 'عرعرة',               fr: "Ar'ara" },
  'אכסאל':              { en: 'Iksal',                  ru: 'Иксаль',            ar: 'إكسال',               fr: 'Iksal' },
  "יפיע":               { en: "Yafi'a",                 ru: 'Яфиа',              ar: 'يافة الناصرة',        fr: "Yafi'a" },
  'שפרעם':              { en: 'Shfaram',                ru: 'Шфарам',            ar: 'شفاعمرو',             fr: 'Shfaram' },
  "סח'נין":             { en: 'Sakhnin',                ru: 'Сахнин',            ar: 'سخنين',               fr: 'Sakhnin' },
  'מגאר':               { en: 'Mghar',                  ru: 'Мгар',              ar: 'مغار',                fr: 'Mghar' },
  'כפר כנא':            { en: 'Kafr Kanna',             ru: 'Кафр-Канна',        ar: 'كفر كنا',             fr: 'Kafr Kanna' },
  'עראבה':              { en: 'Arabe',                  ru: 'Арабе',             ar: 'عرابة',               fr: 'Arabe' },
  'דיר אל-אסד':         { en: 'Deir al-Asad',           ru: 'Дейр-эль-Асад',     ar: 'دير الأسد',           fr: 'Deir al-Asad' },
  "ג'דיידה-מכר":        { en: 'Judeida-Makr',           ru: 'Джудейда-Макр',     ar: 'جديدة المكر',         fr: 'Judeida-Makr' },
  'טמרה':               { en: 'Tamra',                  ru: 'Тамра',             ar: 'طمرة',                fr: 'Tamra' },
  'קריית ארבע':         { en: 'Kiryat Arba',            ru: 'Кирьят-Арба',       ar: 'كريات أربع',          fr: 'Kiryat Arba' },
  'קרית ארבע':          { en: 'Kiryat Arba',            ru: 'Кирьят-Арба',       ar: 'كريات أربع',          fr: 'Kiryat Arba' },
  'אפרת':               { en: 'Efrat',                  ru: 'Эфрат',             ar: 'إيفرات',              fr: 'Efrat' },
  'ביתר עילית':         { en: 'Beitar Illit',           ru: 'Бейтар-Илит',       ar: 'بيتار عيليت',         fr: 'Beitar Illit' },
  'מודיעין עילית':      { en: "Modi'in Illit",          ru: 'Модиин-Илит',       ar: 'موديعين عيليت',       fr: "Modi'in Illit" },
  'מבשרת ציון':         { en: 'Mevaseret Zion',         ru: 'Мевасерет-Цион',    ar: 'مواسيرت تسيون',       fr: 'Mevaseret Zion' },
  'גבעת זאב':           { en: "Givat Ze'ev",            ru: 'Гиват-Зеев',        ar: 'غيفعات زئيف',         fr: "Givat Ze'ev" },
  'כוכב יעקב':          { en: "Kochav Ya'akov",         ru: 'Кохав-Яаков',       ar: 'كوكاف يعكوف',         fr: "Kochav Ya'akov" },

  // ── Gush Dan & Sharon ───────────────────────────────────────────────────────
  'רמת השרון':          { en: 'Ramat HaSharon',         ru: 'Рамат-ха-Шарон',    ar: 'رامات هشارون',        fr: 'Ramat HaSharon' },
  'גני תקווה':          { en: 'Ganei Tikva',            ru: 'Ганей-Тиква',       ar: 'غاني تكفا',           fr: 'Ganei Tikva' },
  'סביון':              { en: 'Savyon',                 ru: 'Савьон',            ar: 'سافيون',              fr: 'Savyon' },
  'אור עקיבא':          { en: 'Or Akiva',               ru: 'Ор-Акива',          ar: 'أور عكيفا',           fr: 'Or Akiva' },
  'כפר שמריהו':         { en: 'Kfar Shmaryahu',         ru: 'Кфар-Шмарьяху',     ar: 'كفار شماريا',         fr: 'Kfar Shmaryahu' },
  'נורדיה':             { en: 'Nordiya',                ru: 'Нордия',            ar: 'نورديا',              fr: 'Nordiya' },
  'תל מונד':            { en: 'Tel Mond',               ru: 'Тель-Монд',         ar: 'تل موند',             fr: 'Tel Mond' },
  'אבן יהודה':          { en: 'Even Yehuda',            ru: 'Эвен-Иегуда',       ar: 'إيفن يهودا',          fr: 'Even Yehuda' },
  'כפר יונה':           { en: 'Kfar Yona',              ru: 'Кфар-Иона',         ar: 'كفار يونا',           fr: 'Kfar Yona' },
  'קדימה-צורן':         { en: 'Kadima-Zoran',           ru: 'Кадима-Цоран',      ar: 'قديما-تسوران',        fr: 'Kadima-Zoran' },
  'אלעד':               { en: "El'ad",                  ru: 'Эль-Ад',            ar: 'إلعاد',               fr: "El'ad" },
  'ראש העין':           { en: 'Rosh HaAyin',            ru: 'Рош-ха-Аин',        ar: 'روش هاعين',           fr: 'Rosh HaAyin' },
  'יהוד-מונוסון':       { en: 'Yehud-Monosson',         ru: 'Йехуд-Моносон',     ar: 'يهود-مونوسون',        fr: 'Yehud-Monosson' },
  'יהוד':               { en: 'Yehud',                  ru: 'Йехуд',             ar: 'يهود',                fr: 'Yehud' },
  'מזכרת בתיה':         { en: 'Mazkeret Batya',         ru: 'Мазкерет-Батья',    ar: 'مزكيريت باتيا',       fr: 'Mazkeret Batya' },
  'גדרה':               { en: 'Gadera',                 ru: 'Гедера',            ar: 'جديرة',               fr: 'Gadera' },
  'שוהם':               { en: 'Shoham',                 ru: 'Шохам',             ar: 'شوهام',               fr: 'Shoham' },
  'בית דגן':            { en: 'Beit Dagan',             ru: 'Бейт-Даган',        ar: 'بيت داغان',           fr: 'Beit Dagan' },
  'חמד':                { en: 'Hemed',                  ru: 'Хемед',             ar: 'حامد',                fr: 'Hemed' },
  "כפר חב\"ד":          { en: 'Kfar Chabad',            ru: 'Кфар-Хабад',        ar: 'كفار حباد',           fr: 'Kfar Chabad' },
  'כפר נטר':            { en: 'Kfar Netter',            ru: 'Кфар-Неттер',       ar: 'كفار نيتر',           fr: 'Kfar Netter' },
  'משמר השבעה':         { en: "Mishmar HaShiv'a",       ru: 'Мишмар-ха-Шева',    ar: 'مشمار هشيفا',         fr: "Mishmar HaShiv'a" },
  'נחשונים':            { en: 'Nahshonim',              ru: 'Нахшоним',          ar: 'نحشونيم',             fr: 'Nahshonim' },
  'בית עריף':           { en: 'Beit Arif',              ru: 'Бейт-Ариф',         ar: 'بيت عريف',            fr: 'Beit Arif' },
  'מגשימים':            { en: 'Magshimim',              ru: 'Магшимим',          ar: 'مغشيميم',             fr: 'Magshimim' },
  'נשר':                { en: 'Nesher',                 ru: 'Нешер',             ar: 'نيشر',                fr: 'Nesher' },
  'קריית אונו':         { en: 'Kiryat Ono',             ru: 'Кирьят-Оно',        ar: 'كريات أونو',          fr: 'Kiryat Ono' },
  'קרית אונו':          { en: 'Kiryat Ono',             ru: 'Кирьят-Оно',        ar: 'كريات أونو',          fr: 'Kiryat Ono' },
  'כפר סירקין':         { en: 'Kfar Sirkin',            ru: 'Кфар-Сиркин',       ar: 'كفار سيركين',         fr: 'Kfar Sirkin' },
  'פרדסיה':             { en: 'Pardesiya',              ru: 'Пардесия',          ar: 'برديسيا',             fr: 'Pardesiya' },
  'צור הדסה':           { en: 'Tsur Hadassa',           ru: 'Цур-Хадасса',       ar: 'تسور حداسا',          fr: 'Tsur Hadassa' },
  'משמר איילון':        { en: 'Mishmar Ayalon',         ru: 'Мишмар-Айялон',     ar: 'مشمار أيالون',        fr: 'Mishmar Ayalon' },
  'מעש':                { en: "Ma'as",                  ru: 'Маас',              ar: 'معص',                 fr: "Ma'as" },
  'גן יבנה':            { en: 'Gan Yavne',              ru: 'Ган-Явне',          ar: 'غان يبني',            fr: 'Gan Yavne' },
  'פלמחים':             { en: 'Palmachim',              ru: 'Пальмахим',         ar: 'بلماحيم',             fr: 'Palmachim' },
  'גזר':                { en: 'Gezer',                  ru: 'Гезер',             ar: 'جيزر',                fr: 'Gezer' },
  'חשמונאים':           { en: 'Hashmonaim',             ru: 'Хашмонаим',         ar: 'حشمونائيم',           fr: 'Hashmonaim' },
  'כפר רות':            { en: 'Kfar Ruth',              ru: 'Кфар-Рут',          ar: 'كفار روت',            fr: 'Kfar Ruth' },
  'בית נחמיה':          { en: 'Beit Nehemia',           ru: 'Бейт-Нехемия',      ar: 'بيت نحيميا',          fr: 'Beit Nehemia' },
  'רמות השבים':         { en: 'Ramot HaShavim',         ru: 'Рамот-ха-Шавим',    ar: 'راموت هشافيم',        fr: 'Ramot HaShavim' },
  'גאולי תימן':         { en: "Ge'ulei Teiman",         ru: 'Геулей-Тейман',     ar: 'غئولي تيمان',         fr: "Ge'ulei Teiman" },
  'בני עטרות':          { en: 'Bnei Atarot',            ru: 'Бней-Атарот',       ar: 'بني عطروت',           fr: 'Bnei Atarot' },
  'עין ורד':            { en: 'Ein Vered',              ru: 'Эйн-Вред',          ar: 'عين فيريد',           fr: 'Ein Vered' },
  'רמתיים':             { en: 'Ramatayim',              ru: 'Раматаим',          ar: 'راماتاييم',           fr: 'Ramatayim' },
  'צור יצחק':           { en: 'Tsur Yitzhak',           ru: 'Цур-Ицхак',         ar: 'تسور يتسحاك',         fr: 'Tsur Yitzhak' },
  'גן שמואל':           { en: 'Gan Shmuel',             ru: 'Ган-Шмуэль',        ar: 'غان شموئيل',          fr: 'Gan Shmuel' },
  'עמיקם':              { en: 'Amikam',                 ru: 'Амикам',            ar: 'أميكام',              fr: 'Amikam' },

  // ── Haifa district ──────────────────────────────────────────────────────────
  'קריית ים':           { en: 'Kiryat Yam',             ru: 'Кирьят-Ям',         ar: 'كريات يام',           fr: 'Kiryat Yam' },
  'קרית ים':            { en: 'Kiryat Yam',             ru: 'Кирьят-Ям',         ar: 'كريات يام',           fr: 'Kiryat Yam' },
  'קריית ביאליק':       { en: 'Kiryat Bialik',          ru: 'Кирьят-Биалик',     ar: 'كريات بياليك',        fr: 'Kiryat Bialik' },
  'קרית ביאליק':        { en: 'Kiryat Bialik',          ru: 'Кирьят-Биалик',     ar: 'كريات بياليك',        fr: 'Kiryat Bialik' },
  'קריית מוצקין':       { en: 'Kiryat Motzkin',         ru: 'Кирьят-Моцкин',     ar: 'كريات موتسكين',       fr: 'Kiryat Motzkin' },
  'קרית מוצקין':        { en: 'Kiryat Motzkin',         ru: 'Кирьят-Моцкин',     ar: 'كريات موتسكين',       fr: 'Kiryat Motzkin' },
  'קריית אתא':          { en: 'Kiryat Ata',             ru: 'Кирьят-Ата',        ar: 'كريات آتا',           fr: 'Kiryat Ata' },
  'קרית אתא':           { en: 'Kiryat Ata',             ru: 'Кирьят-Ата',        ar: 'كريات آتا',           fr: 'Kiryat Ata' },
  'טירת כרמל':          { en: 'Tirat Carmel',           ru: 'Тират-Кармель',     ar: 'طيرة الكرمل',         fr: 'Tirat Carmel' },
  'יקנעם עילית':        { en: "Yokne'am Illit",         ru: 'Йокнеам-Илит',      ar: 'يوكنعام عيليت',       fr: "Yokne'am Illit" },
  "יקנעם":              { en: "Yokne'am",               ru: 'Йокнеам',           ar: 'يوكنعام',             fr: "Yokne'am" },
  "יוקנעם":             { en: "Yokne'am",               ru: 'Йокнеам',           ar: 'يوكنعام',             fr: "Yokne'am" },
  'קיסריה':             { en: 'Caesarea',               ru: 'Кейсария',          ar: 'قيسارية',             fr: 'Césarée' },
  'עתלית':              { en: 'Atlit',                  ru: 'Атлит',             ar: 'عتليت',               fr: 'Atlit' },
  'פרדס חנה-כרכור':    { en: 'Pardes Hanna-Karkur',    ru: 'Пардес-Ханна',      ar: 'برديس حنا-كركور',     fr: 'Pardes Hanna' },
  'פרדס חנה':           { en: 'Pardes Hanna',           ru: 'Пардес-Ханна',      ar: 'برديس حنا',           fr: 'Pardes Hanna' },
  'בנימינה-גבעת עדה':  { en: 'Binyamina-Givat Ada',    ru: 'Биньямина',         ar: 'بنيامينا-غيفعات عدا', fr: 'Binyamina' },
  'בנימינה גבעת עדה':  { en: 'Binyamina-Givat Ada',    ru: 'Биньямина',         ar: 'بنيامينا-غيفعات عدا', fr: 'Binyamina' },
  'בנימינה':            { en: 'Binyamina',              ru: 'Биньямина',         ar: 'بنيامينا',            fr: 'Binyamina' },
  'חדרה':               { en: 'Hadera',                 ru: 'Хадера',            ar: 'الخضيرة',             fr: 'Hadera' },
  'זכרון יעקב':         { en: "Zichron Ya'akov",        ru: 'Зихрон-Яаков',      ar: 'زخرون يعكوف',         fr: "Zichron Ya'akov" },
  'קריית טבעון':        { en: 'Kiryat Tivon',           ru: 'Кирьят-Тивон',      ar: 'كريات تيفعون',        fr: 'Kiryat Tivon' },
  'קרית טבעון':         { en: 'Kiryat Tivon',           ru: 'Кирьят-Тивон',      ar: 'كريات تيفعون',        fr: 'Kiryat Tivon' },
  'קריית יערים':        { en: "Kiryat Ye'arim",         ru: 'Кирьят-Яарим',      ar: 'كريات يعاريم',        fr: "Kiryat Ye'arim" },
  'קרית יערים':         { en: "Kiryat Ye'arim",         ru: 'Кирьят-Яарим',      ar: 'كريات يعاريم',        fr: "Kiryat Ye'arim" },
  'רכסים':              { en: 'Rekhasim',               ru: 'Рехасим',           ar: 'ريحاسيم',             fr: 'Rekhasim' },
  'עומר':               { en: 'Omer',                   ru: 'Омер',              ar: 'عومر',                fr: 'Omer' },
  'מיתר':               { en: 'Metar',                  ru: 'Метар',             ar: 'ميتار',               fr: 'Metar' },
  'להבים':              { en: 'Lehavim',                ru: 'Лехавим',           ar: 'لهاڤيم',              fr: 'Lehavim' },
  'דאלית אל-כרמל':     { en: 'Daliyat al-Karmel',      ru: 'Далийят-эль-Кармель', ar: 'دالية الكرمل',      fr: 'Daliyat al-Karmel' },
  'עספיא':              { en: 'Isfiya',                 ru: 'Исфия',             ar: 'عسفيا',               fr: 'Isfiya' },
  'פוריידיס':           { en: 'Fureidis',               ru: 'Фурейдис',          ar: 'الفريديس',            fr: 'Fureidis' },
  "ג'ת":                { en: "Jat",                    ru: 'Джат',              ar: 'جت',                  fr: 'Jat' },
  'כפר יאסיף':          { en: 'Kafr Yasif',             ru: 'Кафр-Ясиф',         ar: 'كفر ياسيف',           fr: 'Kafr Yasif' },
  'בסמת טבעון':         { en: "Basmat Tab'un",          ru: 'Басмат-Табун',       ar: 'بسمة طبعون',          fr: "Basmat Tab'un" },
  'מנוף':               { en: 'Manof',                  ru: 'Маноф',             ar: 'مانوف',               fr: 'Manof' },

  // ── North ───────────────────────────────────────────────────────────────────
  'קצרין':              { en: 'Katzrin',                ru: 'Кацрин',            ar: 'قصرين',               fr: 'Katzrin' },
  'מטולה':              { en: 'Metula',                 ru: 'Метула',            ar: 'مطولة',               fr: 'Metula' },
  'כפר ורדים':          { en: 'Kfar Vradim',            ru: 'Кфар-Врадим',       ar: 'كفار فراديم',         fr: 'Kfar Vradim' },
  'ראש פינה':           { en: 'Rosh Pinna',             ru: 'Рош-Пина',          ar: 'روش بينا',            fr: 'Rosh Pinna' },
  'שלומי':              { en: 'Shelomi',                ru: 'Шломи',             ar: 'شلومي',               fr: 'Shelomi' },
  'חצור הגלילית':       { en: 'Hazor HaGlilit',         ru: 'Хацор-ха-Глилит',   ar: 'حاتسور هجليلية',      fr: 'Hazor HaGlilit' },
  'טורעאן':             { en: "Tur'an",                 ru: 'Туран',             ar: 'طورعان',              fr: "Tur'an" },
  'יבנאל':              { en: "Yavne'el",               ru: 'Явнеэль',           ar: 'يبنئيل',              fr: "Yavne'el" },
  'כסרא-סמיע':          { en: 'Kisra-Sumei',            ru: 'Кисра-Сумей',       ar: 'كسرى-سميع',           fr: 'Kisra-Sumei' },
  "מג\'ד אל-כרום":      { en: 'Majd al-Krum',           ru: 'Мадж-эль-Крум',     ar: 'مجد الكروم',          fr: 'Majd al-Krum' },
  "מגד אל-כרום":        { en: 'Majd al-Krum',           ru: 'Мадж-эль-Крум',     ar: 'مجد الكروم',          fr: 'Majd al-Krum' },
  "ג'ולס":              { en: 'Julis',                  ru: 'Джулис',            ar: 'جولس',                fr: 'Julis' },
  'דבוריה':             { en: 'Dabburye',               ru: 'Даббурие',          ar: 'دبورية',              fr: 'Dabburye' },
  'דייר חנא':           { en: 'Deir Hanna',             ru: 'Дейр-Ханна',        ar: 'دير حنا',             fr: 'Deir Hanna' },
  "כאוכב אבו אל-היג\'א":{ en: 'Kaokab Abu al-Hija',    ru: 'Кауказ-Абу-эль-Хиджа', ar: 'كوكب أبو الهيجاء', fr: 'Kaokab Abu al-Hija' },
  'ראמה':               { en: 'Rama',                   ru: 'Рама',              ar: 'راما',                fr: 'Rama' },
  "יאנוח-ג\'ת":         { en: 'Yanuh-Jat',              ru: 'Януй-Джат',         ar: 'يانوح جت',            fr: 'Yanuh-Jat' },
  'עיילבון':            { en: 'Eilabun',                ru: 'Эйлабун',           ar: 'عيلبون',              fr: 'Eilabun' },
  'עילוט':              { en: 'Ilut',                   ru: 'Илут',              ar: 'إيلوط',               fr: 'Ilut' },
  'שעב':                { en: "Sha'ab",                 ru: 'Шааб',              ar: 'شعب',                 fr: "Sha'ab" },
  'ריחאניה':            { en: 'Reihaniyye',             ru: 'Рейхания',          ar: 'الريحانية',           fr: 'Reihaniyye' },
  'ביר אל-מכסור':       { en: 'Bir el-Maksur',          ru: 'Бир-эль-Максур',    ar: 'بير المكسور',         fr: 'Bir el-Maksur' },
  "ג'ת (חיפה)":         { en: 'Gat (Haifa)',            ru: 'Гат (Хайфа)',       ar: 'جت (حيفا)',           fr: 'Gat (Haifa)' },
  "בועיינה-נוג\'ידאת":  { en: "Bu'eine-Nujeidat",       ru: 'Буэйне-Нуджейдат',  ar: 'بوعينة-نجيدات',       fr: "Bu'eine-Nujeidat" },
  'בענה':               { en: "Bi'ne",                  ru: 'Бина',              ar: 'بعنة',                fr: "Bi'ne" },
  'טובא-זנגריה':        { en: 'Tuba-Zangariya',         ru: 'Туба-Зангария',     ar: 'طوبا-زنغرية',         fr: 'Tuba-Zangariya' },
  'חורפיש':             { en: 'Hurfeish',               ru: 'Хурфейш',           ar: 'حرفيش',               fr: 'Hurfeish' },
  "ח'ואלד":             { en: 'Khawaled',               ru: 'Хавалед',           ar: 'خوالد',               fr: 'Khawaled' },
  "בית ג'ן":            { en: 'Beit Jann',              ru: 'Бейт-Джанн',        ar: 'بيت جن',              fr: 'Beit Jann' },
  "ג'ת (מרכז)":         { en: 'Jat (Center)',           ru: 'Джат (Центр)',      ar: 'جت',                  fr: 'Jat (Centre)' },
  'נחף':                { en: 'Nahef',                  ru: 'Нахеф',             ar: 'نحف',                 fr: 'Nahef' },
  'כפר מנדא':           { en: 'Kafr Manda',             ru: 'Кафр-Манда',        ar: 'كفر مندا',            fr: 'Kafr Manda' },
  'ריינה':              { en: 'Reineh',                 ru: 'Рейна',             ar: 'رينة',                fr: 'Reineh' },
  'ירכא':               { en: 'Yarka',                  ru: 'Ярка',              ar: 'يركا',                fr: 'Yarka' },
  'עין מאהל':           { en: 'Ein Mahel',              ru: 'Эйн-Махаль',        ar: 'عين ماهل',            fr: 'Ein Mahel' },
  'כאבול':              { en: 'Kabul',                  ru: 'Кабуль',            ar: 'كابول',               fr: 'Kabul' },
  'מגדל שמס':           { en: 'Majdal Shams',           ru: 'Мадждаль-Шамс',     ar: 'مجدل شمس',            fr: 'Majdal Shams' },
  "ע'ג'ר":              { en: 'Ghajar',                 ru: 'Гаджар',            ar: 'الغجر',               fr: 'Ghajar' },
  "שבלי-אום אל-גנם":    { en: 'Shibli-Umm al-Ghanam',  ru: 'Шибли-Умм аль-Ганам', ar: 'شبلي - أم الغنم',   fr: 'Shibli-Umm al-Ghanam' },

  // ── South & Negev ────────────────────────────────────────────────────────────
  'נבטים':              { en: 'Nevatim',                ru: 'Неватим',           ar: 'نيفاتيم',             fr: 'Nevatim' },
  'ירוחם':              { en: 'Yeruham',                ru: 'Ерухам',            ar: 'يروحام',              fr: 'Yeruham' },

  // ── Golan Heights ───────────────────────────────────────────────────────────
  'מרום גולן':          { en: 'Merom Golan',            ru: 'Мером-Голан',       ar: 'ميروم غولان',         fr: 'Merom Golan' },

  // ── Triangle & Arab communities ─────────────────────────────────────────────
  'אבו סנאן':           { en: 'Abu Sinan',              ru: 'Абу-Синан',         ar: 'أبو سنان',            fr: 'Abu Sinan' },
  'אבו גוש':            { en: 'Abu Ghosh',              ru: 'Абу-Гош',           ar: 'أبو غوش',             fr: 'Abu Ghosh' },
  'זרזיר':              { en: 'Zarzir',                 ru: 'Зарзир',            ar: 'زرزير',               fr: 'Zarzir' },

  // ── Judea & Samaria ──────────────────────────────────────────────────────────
  'אדם':                { en: 'Adam',                   ru: 'Адам',              ar: 'آدام',                fr: 'Adam' },
  'עופרה':              { en: 'Ofra',                   ru: 'Офра',              ar: 'عوفرا',               fr: 'Ofra' },
  'אלפי מנשה':          { en: 'Alfei Menashe',          ru: 'Алфей-Менаше',      ar: 'ألفي منشه',           fr: 'Alfei Menashe' },
  'קרני שומרון':        { en: 'Karnei Shomron',         ru: 'Карней-Шомрон',     ar: 'كرني شومرون',         fr: 'Karnei Shomron' },
  'עמנואל':             { en: 'Emmanuel',               ru: 'Эммануэль',         ar: 'عمانوئيل',            fr: 'Emmanuel' },
  'בית אריה':           { en: 'Beit Arye',              ru: 'Бейт-Арье',         ar: 'بيت أريه',            fr: 'Beit Arye' },
  'בית חורון':          { en: 'Beit Horon',             ru: 'Бейт-Хорон',        ar: 'بيت حورون',           fr: 'Beit Horon' },
  'גוש עציון':          { en: 'Gush Etzion',            ru: 'Гуш-Эцион',         ar: 'غوش عتسيون',          fr: 'Gush Etzion' },
  'מעלה אפרים':         { en: "Ma'ale Efraim",          ru: 'Маале-Эфраим',      ar: 'معاليه أفرايم',       fr: "Ma'ale Efraim" },
  'שילה':               { en: 'Shilo',                  ru: 'Шило',              ar: 'شيلو',                fr: 'Shilo' },
  'אלון מורה':          { en: 'Elon Moreh',             ru: 'Элон-Море',         ar: 'إيلون موريه',         fr: 'Elon Moreh' },
  'דולב':               { en: 'Dolev',                  ru: 'Долев',             ar: 'دوليف',               fr: 'Dolev' },
  'קדומים':             { en: 'Kedumim',                ru: 'Кедумим',           ar: 'كيدوميم',             fr: 'Kedumim' },
  'גבעת ברנר':          { en: 'Givat Brenner',          ru: 'Гиват-Бреннер',     ar: 'غيفعات برينر',        fr: 'Givat Brenner' },
  'עלי':                { en: 'Eli',                    ru: 'Эли',               ar: 'عيلي',                fr: 'Eli' },
  'תקוע':               { en: 'Tekoa',                  ru: 'Текоа',             ar: 'تقوع',                fr: 'Tekoa' },
  'גבע בנימין':         { en: 'Geva Binyamin',          ru: 'Гева-Биньямин',     ar: 'غيفع بنيامين',        fr: 'Geva Binyamin' },
  'מצפה יריחו':         { en: 'Mitzpe Yeriho',          ru: 'Мицпе-Иерихон',     ar: 'متسبه يريحو',         fr: 'Mitzpe Yeriho' },
  'פסגות':              { en: 'Psagot',                 ru: 'Псагот',            ar: 'بسغوت',               fr: 'Psagot' },
  'אורנית':             { en: 'Oranit',                 ru: 'Оранит',            ar: 'أورانيت',             fr: 'Oranit' },
  'ברוכין':             { en: 'Brukhim',                ru: 'Брухим',            ar: 'بروخين',              fr: 'Brukhim' },
  'ברקן':               { en: 'Barkan',                 ru: 'Баркан',            ar: 'بركان',               fr: 'Barkan' },
  'שועפאט':             { en: "Shu'fat",                ru: 'Шуафат',            ar: 'شعفاط',               fr: "Shu'fat" },
  'פקיעין (בוקייעה)':   { en: "Peki'in",               ru: 'Пкиин',             ar: 'البقيعة',             fr: "Peki'in" },

  // ── Additional localities / misc ─────────────────────────────────────────────
  'אזור':               { en: 'Azor',                   ru: 'Азор',              ar: 'عزور',                fr: 'Azor' },
  'שערי תקווה':         { en: "Sha'are Tikva",          ru: 'Шаарей-Тиква',      ar: 'شعاري تكفا',          fr: "Sha'are Tikva" },
  'מעלות':              { en: "Ma'alot",                ru: 'Маалот',            ar: 'معلوت',               fr: "Ma'alot" },
  'גבעת עדה':           { en: 'Givat Ada',              ru: 'Гиват-Ада',         ar: 'غيفعات عدا',          fr: 'Givat Ada' },
  'זמר':                { en: 'Zemer',                  ru: 'Земер',             ar: 'زيمر',                fr: 'Zemer' },
  'בוקעאתא':            { en: "Buq'ata",                ru: 'Буката',            ar: 'بقعاثا',              fr: "Buq'ata" },
  "מסעדה":              { en: "Mas'ada",                ru: 'Масада',            ar: 'مسعدة',               fr: "Mas'ada" },
  'כפר חסידים':         { en: 'Kfar Hasidim',           ru: 'Кфар-Хасидим',      ar: 'كفار حسيديم',         fr: 'Kfar Hasidim' },
  'פוריה':              { en: 'Poriya',                 ru: 'Пория',             ar: 'بوريا',               fr: 'Poriya' },
  'מעגן מיכאל':         { en: "Ma'agan Michael",        ru: 'Маган-Михаэль',     ar: 'ماعان مايكل',         fr: "Ma'agan Michael" },
  'מורשת':              { en: 'Moreshet',               ru: 'Морешет',           ar: 'موريشيت',             fr: 'Moreshet' },
  'כפר מצר':            { en: 'Kafr Misr',              ru: 'Кафр-Мисер',        ar: 'كفر مصر',             fr: 'Kafr Misr' },
  'אור הנר':            { en: 'Or HaNer',               ru: 'Ор-ха-Нер',         ar: 'أور هنر',             fr: 'Or HaNer' },
  'בית יוסף':           { en: 'Beit Yosef',             ru: 'Бейт-Йосеф',        ar: 'بيت يوسف',            fr: 'Beit Yosef' },
  'מצובה':              { en: 'Mazzuva',                ru: 'Маззува',           ar: 'متسوبا',              fr: 'Mazzuva' },
  'ניר עם':             { en: 'Nir Am',                 ru: 'Нир-Ам',            ar: 'نير عام',             fr: 'Nir Am' },
  'נחל עוז':            { en: 'Nahal Oz',               ru: 'Нахаль-Оз',         ar: 'نهال عوز',            fr: 'Nahal Oz' },

  // ── Kibbutzim ────────────────────────────────────────────────────────────────
  'אפיקים':             { en: 'Afikim' },
  'אפיק':               { en: 'Afik' },
  'בארי':               { en: "Be'eri" },
  'בית אלפא':           { en: 'Beit Alfa' },
  'בית גוברין':         { en: 'Beit Guvrin' },
  'בית העמק':           { en: 'Beit HaEmek' },
  'בית הערבה':          { en: 'Beit HaArava' },
  'בית השיטה':          { en: 'Beit HaShitta' },
  'בית זרע':            { en: 'Beit Zera' },
  'בית קשת':            { en: 'Beit Keshet' },
  "דגניה א'":           { en: 'Degania Alef' },
  "דגניה ב'":           { en: 'Degania Bet' },
  'דן':                 { en: 'Dan' },
  'דפנה':               { en: 'Dafna' },
  'האון':               { en: 'Haon' },
  'הגושרים':            { en: 'HaGosherim' },
  'הבונים':             { en: 'HaBonnim' },
  'הזורע':              { en: 'HaZorea' },
  'גבים':               { en: 'Gevim' },
  'גבע':                { en: 'Geva' },
  'גבת':                { en: 'Gevat' },
  'גדות':               { en: 'Gadot' },
  'גינוסר':             { en: 'Ginosar' },
  'גיניגר':             { en: 'Ginnegar' },
  'גל-און':             { en: 'Gal On' },
  'גל און':             { en: 'Gal On' },
  'דורות':              { en: 'Dorot' },
  'דליה':               { en: 'Daliya' },
  'ורד יריחו':          { en: 'Vered Yericho' },
  'חניתה':              { en: 'Hanita' },
  'חפץ חיים':           { en: 'Hafetz Hayyim' },
  'חפצי-בה':            { en: 'Hefzi-Bah' },
  'טירת צבי':           { en: 'Tirat Zvi' },
  'יגור':               { en: 'Yagur' },
  'יד מרדכי':           { en: 'Yad Mordechai' },
  'יחיעם':              { en: "Yehi'am" },
  'יטבתה':              { en: 'Yotvata' },
  'כברי':               { en: 'Kabri' },
  'כפר בלום':           { en: 'Kfar Blum' },
  'כפר גלעדי':          { en: "Kfar Gil'adi" },
  'כפר החורש':          { en: 'Kfar HaHoresh' },
  'כפר המכבי':          { en: 'Kfar HaMaccabi' },
  'כפר הנשיא':          { en: 'Kfar HaNasi' },
  'כפר חרוב':           { en: 'Kfar Haruv' },
  'כפר מסריק':          { en: 'Kfar Masaryk' },
  'כפר רופין':          { en: 'Kfar Ruppin' },
  'כפר סאלד':           { en: 'Kfar Szold' },
  'כפר עזה':            { en: 'Kfar Azza' },
  'כינרת':              { en: 'Kinneret' },
  'לביא':               { en: 'Lavi' },
  'לוחמי הגיטאות':      { en: 'Lohamei HaGetaot' },
  'לוטן':               { en: 'Lotan' },
  'מגידו':              { en: 'Megiddo' },
  'מגן':                { en: 'Magen' },
  'מחניים':             { en: 'Mahanayim' },
  'מזרע':               { en: 'Mizra' },
  'מנחמיה':             { en: 'Menahamiya' },
  'מנרה':               { en: 'Menarah' },
  'מסדה':               { en: 'Massada' },
  'מעוז חיים':          { en: "Ma'oz Hayyim" },
  'מעין ברוך':          { en: "Ma'ayan Baruch" },
  'מעין צבי':           { en: "Ma'ayan Zvi" },
  'מרחביה':             { en: 'Merhavya' },
  'משגב עם':            { en: 'Misgav Am' },
  'משמר דוד':           { en: 'Mishmar David' },
  'משמר הירדן':         { en: 'Mishmar HaYarden' },
  'משמר הנגב':          { en: 'Mishmar HaNegev' },
  'משמר העמק':          { en: 'Mishmar HaEmek' },
  'משמר השרון':         { en: 'Mishmar HaSharon' },
  'נגבה':               { en: 'Negba' },
  'נהלל':               { en: 'Nahalal' },
  'נחשולים':            { en: 'Nahsholim' },
  "נעם":                { en: "Na'an" },
  'ניר אליהו':          { en: 'Nir Eliyahu' },
  'ניר דוד':            { en: 'Nir David' },
  'ניר עוז':            { en: 'Nir Oz' },
  'ניר יצחק':           { en: 'Nir Yitzhak' },
  'נירים':              { en: 'Nirim' },
  'עין גב':             { en: 'Ein Gev' },
  'עין גדי':            { en: 'Ein Gedi' },
  'עין דור':            { en: 'Ein Dor' },
  'עין החורש':          { en: 'Ein HaHoresh' },
  'עין השופט':          { en: 'Ein HaShofet' },
  'עין חרוד':           { en: 'Ein Harod' },
  'עין כרמל':           { en: 'Ein Karmel' },
  'עין שמר':            { en: 'Ein Shemer' },
  'עין צורים':          { en: 'Ein Tzurim' },
  'עין זיוון':          { en: 'Ein Ziwan' },
  "עין הנצי\"ב":        { en: 'Ein HaNatziv' },
  'עין המפרץ':          { en: 'Ein HaMifraatz' },
  'ראש הנקרה':          { en: 'Rosh HaNikra' },
  'רביבים':             { en: 'Revivim' },
  'רוחמה':              { en: 'Ruhama' },
  'רמות נפתלי':         { en: 'Ramot Naftali' },
  'רמת דוד':            { en: 'Ramat David' },
  'רמת יוחנן':          { en: 'Ramat Yohanan' },
  'רמת מגשימים':        { en: 'Ramat Magshimim' },
  'רמת רחל':            { en: 'Ramat Rahel' },
  'שדות ים':            { en: 'Sdot Yam' },
  'שובל':               { en: 'Shoval' },
  'שמיר':               { en: 'Shamir' },
  'שניר':               { en: 'Senir' },
  'שפיים':              { en: 'Shefayim' },
  'שריד':               { en: 'Sarid' },
  'תל יוסף':            { en: 'Tel Yosef' },
  'תל קציר':            { en: 'Tel Katzir' },
  'ארז':                { en: 'Erez' },
  'ברור חיל':           { en: 'Beror Hayil' },
  'גברעם':              { en: "Gevar'am" },
  'זיקים':              { en: 'Zikim' },
  'כרם שלום':           { en: 'Kerem Shalom' },
  'מפלסים':             { en: 'Mefallesim' },
  'סאסא':               { en: 'Sasa' },
  'קבוצת יבנה':         { en: 'Kvutzat Yavne' },
  'רעים':               { en: "Re'im" },
  'אורטל':              { en: 'Ortal' },
  'נמרוד':              { en: 'Nimrod' },
  'גשר הזיו':           { en: 'Gesher HaZiv' },
  'כרם בן זמרה':        { en: 'Kerem Ben Zimra' },
  'נצר סרני':           { en: 'Netzer Sereni' },

  // ── Moshavim ─────────────────────────────────────────────────────────────────
  'אביגדור':            { en: 'Avigdor' },
  'אביחיל':             { en: 'Avihayil' },
  'אביטל':              { en: 'Avital' },
  'אבן שמואל':          { en: 'Even Shmuel' },
  'אגור':               { en: 'Agur' },
  'אהוד':               { en: 'Ehud' },
  'אחיטוב':             { en: 'Ahituv' },
  'אחיסמך':             { en: 'Ahisamach' },
  'אחיעזר':             { en: "Ahi'ezer" },
  'איבים':              { en: 'Ibbim' },
  'איילת השחר':         { en: 'Ayelet HaShahar' },
  'אילניה':             { en: 'Ilaniya' },
  'אל-רום':             { en: 'El-Rom' },
  'אלון שבות':          { en: 'Allon Shvut' },
  'אלוני אבא':          { en: 'Allone Abba' },
  'אליכין':             { en: 'Elyakhin' },
  'אליקים':             { en: 'Elyakim' },
  'אלישיב':             { en: 'Elyashiv' },
  'אמונים':             { en: 'Emunim' },
  'אמירים':             { en: 'Amirim' },
  'אמציה':              { en: 'Amazya' },
  'ארגמן':              { en: 'Argaman' },
  'אשבול':              { en: 'Eshbol' },
  'אשכולות':            { en: 'Eshkolot' },
  'באר טוביה':          { en: "Be'er Tuvia" },
  'בארות יצחק':         { en: "Be'erot Yitzhak" },
  'בארותיים':           { en: "Be'erotayim" },
  'בוסתן הגליל':        { en: 'Bustan HaGalil' },
  'בורגתה':             { en: 'Burgeta' },
  'בחן':                { en: 'Bahan' },
  'בית אורן':           { en: 'Beit Oren' },
  'בית אלעזרי':         { en: "Beit El'azari" },
  'בית גמליאל':         { en: 'Beit Gamliel' },
  'בית הלוי':           { en: 'Beit HaLevi' },
  'בית הלל':            { en: 'Beit Hillel' },
  'בית זיד':            { en: 'Beit Zeid' },
  'בית זית':            { en: 'Beit Zayit' },
  'בית חירות':          { en: 'Beit Herut' },
  'בית חלקיה':          { en: 'Beit Hilkiya' },
  'בית חנן':            { en: 'Beit Hanan' },
  'בית חנניה':          { en: 'Beit Hananya' },
  'בית יהושע':          { en: 'Beit Yehoshua' },
  'בית ינאי':           { en: 'Beit Yanai' },
  'בית יצחק-שער חפר':  { en: "Beit Yitzhak-Sha'ar Hefer" },
  'בית לחם הגלילית':    { en: 'Bethlehem of Galilee' },
  'בית מאיר':           { en: "Beit Me'ir" },
  'בית ניר':            { en: 'Beit Nir' },
  'בית עובד':           { en: 'Beit Oved' },
  'בית עזרא':           { en: 'Beit Ezra' },
  'בית צבי':            { en: 'Beit Zvi' },
  'בית קמה':            { en: 'Beit Kama' },
  'בית שערים':          { en: "Beit She'arim" },
  'בית שקמה':           { en: 'Beit Shikma' },
  'ביתן אהרן':          { en: 'Bitan Aharon' },
  'בלפוריה':            { en: 'Balfuriya' },
  'בן זכאי':            { en: 'Ben Zakkay' },
  'בן עמי':             { en: 'Ben Ami' },
  'בני דרום':           { en: 'Bnei Darom' },
  'בני דרור':           { en: 'Bnei Dror' },
  'בני יהודה':          { en: 'Bnei Yehuda' },
  'בני ציון':           { en: 'Bnei Zion' },
  'בני ראם':            { en: "Bnei Re'em" },
  'ברכיה':              { en: 'Berechya' },
  'ברקאי':              { en: 'Barkai' },
  'ברקת':               { en: 'Bareket' },
  'בת חן':              { en: 'Bat Hen' },
  'בת חפר':             { en: 'Bat Hefer' },
  'בת שלמה':            { en: 'Bat Shlomo' },
  'גאולים':             { en: "Ge'ulim" },
  'גאליה':              { en: "Ge'alya" },
  'גבעת אלה':           { en: 'Givat Ela' },
  'גבעת השלושה':        { en: 'Givat HaShelosha' },
  'גבעת חיים':          { en: 'Givat Hayyim' },
  "גבעת ח\"ן":          { en: 'Givat Hen' },
  'גבעת יואב':          { en: "Givat Yo'av" },
  'גבעת ישעיהו':        { en: 'Givat Yeshayahu' },
  'גבעת עוז':           { en: 'Givat Oz' },
  'גדיש':               { en: 'Gadish' },
  'גון':                { en: 'Gonen' },
  'גורן':               { en: 'Goren' },
  'גזית':               { en: 'Gazit' },
  'גיאה':               { en: "Ge'a" },
  'גיבתון':             { en: 'Gibbeton' },
  'גיזו':               { en: 'Gizo' },
  'גילון':              { en: 'Gilon' },
  'גילת':               { en: 'Gilat' },
  'גיתה':               { en: 'Gitta' },
  'גיתית':              { en: 'Gittit' },
  'גלאון':              { en: "Gal'on" },
  'גליל ים':            { en: 'Gelil Yam' },
  'גמזו':               { en: 'Gimzo' },
  'גן הדרום':           { en: 'Gan HaDarom' },
  'גן השומרון':         { en: 'Gan HaShomron' },
  'גן חיים':            { en: 'Gan Hayyim' },
  'גן יאשיה':           { en: 'Gan Yoshiya' },
  'גן נר':              { en: 'Gan Ner' },
  'גן שורק':            { en: 'Gan Sorek' },
  'גן שלמה':            { en: 'Gan Shlomo' },
  'גנות':               { en: 'Gannot' },
  'גנות הדר':           { en: 'Gannot Hadar' },
  'גני הדר':            { en: 'Ganei Hadar' },
  'גני טל':             { en: 'Ganei Tal' },
  'גני יוחנן':          { en: 'Ganei Yohanan' },
  'גני עם':             { en: 'Ganei Am' },
  'גפן':                { en: 'Gefen' },
  'גשר':                { en: 'Gesher' },
  'דבורה':              { en: 'Devora' },
  'דברת':               { en: 'Daverat' },
  'דישון':              { en: 'Dishon' },
  'דלתון':              { en: 'Dalton' },
  'הדר עם':             { en: 'Hadar Am' },
  'הודיה':              { en: 'Hodiya' },
  'הודיות':             { en: 'Hodayot' },
  'הושעיה':             { en: "Hosha'aya" },
  'היוגב':              { en: 'HaYogev' },
  'הר אדר':             { en: 'Har Adar' },
  'הר גילה':            { en: 'Har Gilo' },
  'הר עמשא':            { en: 'Har Amasa' },
  'הראל':               { en: "Har'el" },
  'הררית':              { en: 'Hararit' },
  'זוהר':               { en: 'Zohar' },
  'זיתן':               { en: 'Zetan' },
  'זכריה':              { en: 'Zekharia' },
  'זמרת':               { en: 'Zimrat' },
  'חבצלת השרון':        { en: 'Havatzelet HaSharon' },
  'חגור':               { en: 'Hagor' },
  'חגלה':               { en: 'Hogla' },
  'חדיד':               { en: 'Hadid' },
  'חולדה':              { en: 'Hulda' },
  'חוסן':               { en: 'Hosen' },
  'חיבת ציון':          { en: 'Hibbat Zion' },
  'חירות':              { en: 'Herut' },
  'חלץ':                { en: 'Helez' },
  'חמדיה':              { en: 'Hamadya' },
  'חמרה':               { en: 'Hamra' },
  'חניאל':              { en: "Hanni'el" },
  'חנתון':              { en: 'Hannaton' },
  'חצב':                { en: 'Hatzav' },
  'חצבה':               { en: 'Hatzeva' },
  'חרב לאת':            { en: "Herev Le'et" },
  'חרמש':               { en: 'Hermesh' },
  'טל שחר':             { en: 'Tal Shahar' },
  'טל-אל':              { en: 'Tal-El' },
  'טלמון':              { en: 'Talmon' },
  'יד בנימין':          { en: 'Yad Binyamin' },
  'יד חנה':             { en: 'Yad Hanna' },
  'יד נתן':             { en: 'Yad Natan' },
  'יהל':                { en: 'Yahel' },
  'יובל':               { en: 'Yuval' },
  'יובלים':             { en: 'Yuvalim' },
  'יודפת':              { en: 'Yodfat' },
  'יונתן':              { en: 'Yonatan' },
  'יזרעאל':             { en: "Yizre'el" },
  'יכיני':              { en: 'Yakhini' },
  'ינון':               { en: 'Yinnon' },
  'יסוד המעלה':         { en: "Yesod HaMa'ala" },
  'יסודות':             { en: 'Yesodot' },
  'יעד':                { en: "Ya'ad" },
  'יערה':               { en: "Ya'ara" },
  'יפית':               { en: 'Yafit' },
  'יפעת':               { en: "Yif'at" },
  'יצהר':               { en: 'Yitzhar' },
  'יציץ':               { en: 'Yaziz' },
  'יקום':               { en: 'Yakum' },
  'יראון':              { en: "Yir'on" },
  'ירחיב':              { en: 'Yarhiv' },
  'ירקונה':             { en: 'Yarkona' },
  'יתד':                { en: 'Yated' },
  'כדיתה':              { en: 'Kaddita' },
  'כוכב השחר':          { en: 'Kokhav HaShahar' },
  'כוכב יאיר':          { en: 'Kokhav Yair' },
  'כוכב מיכאל':         { en: 'Kokhav Michael' },
  'כיסופים':            { en: 'Kissufim' },
  'כפר אביב':           { en: 'Kfar Aviv' },
  'כפר אדומים':         { en: 'Kfar Adumim' },
  'כפר אוריה':          { en: 'Kfar Uria' },
  'כפר אחים':           { en: 'Kfar Ahim' },
  'כפר ביאליק':         { en: 'Kfar Bialik' },
  'כפר בן נון':         { en: 'Kfar Bin Nun' },
  'כפר ברוך':           { en: 'Kfar Baruch' },
  'כפר גדעון':          { en: 'Kfar Gidon' },
  'כפר גלים':           { en: 'Kfar Gallim' },
  'כפר גליקסון':        { en: 'Kfar Glikson' },
  'כפר דניאל':          { en: 'Kfar Daniel' },
  'כפר הס':             { en: 'Kfar Hess' },
  'כפר ויתקין':         { en: 'Kfar Vitkin' },
  'כפר ורבורג':         { en: 'Kfar Warburg' },
  'כפר זיתים':          { en: 'Kfar Zeitim' },
  'כפר חושן':           { en: 'Kfar Hoshen' },
  'כפר חיטים':          { en: 'Kfar Hittim' },
  'כפר חיים':           { en: 'Kfar Hayyim' },
  'כפר חנניה':          { en: 'Kfar Hananya' },
  'כפר טרומן':          { en: 'Kfar Truman' },
  'כפר ידידיה':         { en: 'Kfar Yedidya' },
  'כפר יהושע':          { en: 'Kfar Yehoshua' },
  'כפר יחזקאל':         { en: 'Kfar Yehezkel' },
  'כפר כמא':            { en: 'Kafr Kama' },
  'כפר מונש':           { en: 'Kfar Monash' },
  'כפר מימון':          { en: 'Kfar Maimon' },
  'כפר מנחם':           { en: 'Kfar Menahem' },
  'כפר מרדכי':          { en: 'Kfar Mordechai' },
  'כפר עציון':          { en: 'Kfar Etzion' },
  'כפר פינס':           { en: 'Kfar Pines' },
  'כפר קיש':            { en: 'Kfar Kish' },
  'כפר ראש הנקרה':      { en: 'Kfar Rosh HaNikra' },
  'כפר שמאי':           { en: 'Kfar Shamai' },
  'כפר שמואל':          { en: 'Kfar Shmuel' },
  'כפר תבור':           { en: 'Kfar Tavor' },
  'כפר תפוח':           { en: 'Kfar Tapuah' },
  'כרכום':              { en: 'Karkom' },
  'כרמי יוסף':          { en: 'Karme Yosef' },
  'כרמי צור':           { en: 'Karme Tzur' },
  'כרמיה':              { en: 'Karmiya' },
  'לבון':               { en: 'Lavon' },
  'לבנים':              { en: 'Livnim' },
  'להב':                { en: 'Lahav' },
  'להבות הבשן':         { en: 'Lahavot HaBashan' },
  'להבות חביבה':        { en: 'Lahavot Haviva' },
  'לוזית':              { en: 'Luzit' },
  'לוטם':               { en: 'Lotem' },
  'לחיש':               { en: 'Lakhish' },
  'לקיש':               { en: 'Lakhish' },
  'לפיד':               { en: 'Lappid' },
  'מאור':               { en: "Ma'or" },
  'מבוא ביתר':          { en: 'Mevo Beitar' },
  'מבוא דותן':          { en: 'Mevo Dotan' },
  'מבוא חורון':         { en: 'Mevo Horon' },
  'מבוא חמה':           { en: 'Mevo Hamma' },
  'מבוא מודיעים':       { en: "Mevo Modi'im" },
  'מבועים':             { en: "Mabbu'im" },
  'מבטחים':             { en: 'Mivtahim' },
  'מגדל':               { en: 'Migdal' },
  'מגדל עוז':           { en: 'Migdal Oz' },
  'מגדים':              { en: 'Megadim' },
  'מגל':                { en: 'Maggal' },
  'מולדת':              { en: 'Moledet' },
  'מורן':               { en: 'Moran' },
  'מזור':               { en: 'Mazor' },
  'מחולה':              { en: 'Mehola' },
  'מטע':                { en: 'Matta' },
  'מי עמי':             { en: 'Mei Ami' },
  'מירון':              { en: 'Meron' },
  'מכורה':              { en: 'Mekhora' },
  'מלאה':               { en: "Mele'a" },
  'מלילות':             { en: 'Melilot' },
  'מלכיה':              { en: 'Malkiya' },
  'מנוחה':              { en: 'Menuha' },
  'מנות':               { en: 'Manot' },
  'מסד':                { en: 'Massad' },
  'מסילות':             { en: 'Mesilot' },
  'מסילת ציון':         { en: 'Mesilat Zion' },
  'מסלול':              { en: 'Maslul' },
  'מעברות':             { en: "Ma'abarot" },
  'מעגן':               { en: "Ma'agan" },
  'מעון':               { en: "Ma'on" },
  'מעונה':              { en: "Me'ona" },
  'מעיליא':             { en: "Mi'ilya" },
  'מעלה גלבוע':         { en: "Ma'ale Gilboa" },
  'מעלה גמלא':          { en: "Ma'ale Gamla" },
  'מעלה החמישה':        { en: "Ma'ale HaHamisha" },
  'מעלה לבונה':         { en: "Ma'ale Levona" },
  'מעלה מכמש':          { en: "Ma'ale Mikhmas" },
  'מעלה עמוס':          { en: "Ma'ale Amos" },
  'מעלה שומרון':        { en: "Ma'ale Shomron" },
  'מענית':              { en: "Ma'anit" },
  'מצליח':              { en: 'Matzliah' },
  'מצפה אבי"ב':         { en: 'Mitzpe Aviv' },
  'מצפה אילן':          { en: 'Mitzpe Ilan' },
  'מצפה נטופה':         { en: 'Mitzpe Netofa' },
  'מצפה שלם':           { en: 'Mitzpe Shalem' },
  'מצר':                { en: 'Mezer' },
  'מרגליות':            { en: 'Margaliot' },
  'מרכז שפירא':         { en: 'Merkaz Shapira' },
  'משאבי שדה':          { en: "Mash'abe Sade" },
  'משהד':               { en: 'Meshhed' },
  'משואה':              { en: 'Masua' },
  'משואות יצחק':        { en: 'Massuot Yitzhak' },
  'משכיות':             { en: 'Maskiyot' },
  'משמרות':             { en: 'Mishmarot' },
  'משמרת':              { en: 'Mishmeret' },
  'מתן':                { en: 'Mattan' },
  'מתת':                { en: 'Mattat' },
  'מתתיהו':             { en: 'Mattityahu' },
  'נאות גולן':          { en: "Ne'ot Golan" },
  'נאות הכיכר':         { en: "Ne'ot HaKikar" },
  'נאות מרדכי':         { en: "Ne'ot Mordechai" },
  'נגוהות':             { en: 'Negohot' },
  'נהורה':              { en: 'Nehora' },
  'נוב':                { en: 'Nov' },
  'נוגה':               { en: 'Noga' },
  'נווה אור':           { en: 'Neve Or' },
  'נווה אטי"ב':         { en: 'Neve Ativ' },
  'נווה אילן':          { en: 'Neve Ilan' },
  'נווה איתן':          { en: 'Neve Eitan' },
  'נווה דניאל':         { en: 'Neve Daniel' },
  'נווה זוהר':          { en: 'Neve Zohar' },
  'נווה זיו':           { en: 'Neve Ziv' },
  'נווה ים':            { en: 'Neve Yam' },
  'נווה ימין':          { en: 'Neve Yamin' },
  'נווה ירק':           { en: 'Neve Yaraq' },
  'נווה מיכאל':         { en: 'Neve Michael' },
  'נווה שלום':          { en: 'Neve Shalom' },
  'נועם':               { en: "No'am" },
  'נוף איילון':         { en: 'Nof Ayalon' },
  'נופים':              { en: 'Nofim' },
  'נופית':              { en: 'Nofit' },
  'נורית':              { en: 'Nurit' },
  'נחושה':              { en: 'Nehusha' },
  'נחלה':               { en: 'Nahala' },
  'נחלים':              { en: 'Nehalim' },
  'נחם':                { en: 'Naham' },
  'נחשון':              { en: 'Nahshon' },
  'נטועה':              { en: "Netu'a" },
  'נטעים':              { en: "Neta'im" },
  'נטף':                { en: 'Nataf' },
  'ניל"י':              { en: 'Nili' },
  'ניצן':               { en: 'Nitzan' },
  'ניצנה':              { en: 'Nitzana' },
  'ניצני עוז':          { en: 'Nitzanei Oz' },
  'ניצנים':             { en: 'Nitzanim' },
  'ניר בנים':           { en: 'Nir Banim' },
  'ניר גלים':           { en: 'Nir Gallim' },
  'ניר יפה':            { en: 'Nir Yafe' },
  'ניר ישראל':          { en: 'Nir Yisrael' },
  'ניר משה':            { en: 'Nir Moshe' },
  'ניר עציון':          { en: 'Nir Etzion' },
  'ניר עקיבא':          { en: 'Nir Akiva' },
  'ניר צבי':            { en: 'Nir Tzvi' },
  'נירית':              { en: 'Nirit' },
  'נס הרים':            { en: 'Nes Harim' },
  'נצר חזני':           { en: 'Netzer Hazani' },
  'נתיב הגדוד':         { en: 'Netiv HaGedud' },
  'נתיב הל"ה':          { en: 'Netiv HaLamed-He' },
  'נתיב העשרה':         { en: 'Netiv HaAsara' },
  'נתיב השיירה':        { en: 'Netiv HaShayara' },
  'סגולה':              { en: 'Segula' },
  'סופה':               { en: 'Sufa' },
  'סמר':                { en: 'Samar' },
  'סעד':                { en: "Sa'ad" },
  'סער':                { en: "Sa'ar" },
  'ספיר':               { en: 'Sappir' },
  'סתריה':              { en: 'Sitriya' },
  'עבדון':              { en: 'Avdon' },
  'עברון':              { en: 'Evron' },
  'עדי':                { en: 'Adi' },
  'עוצם':               { en: 'Ozem' },
  'עזריאל':             { en: "Azri'el" },
  'עזריה':              { en: 'Azarya' },
  'עזריקם':             { en: 'Azrikam' },
  'עטרת':               { en: 'Ateret' },
  'עידן':               { en: 'Iddan' },
  'עיינות':             { en: 'Ayanot' },
  'עין איילה':          { en: 'Ein Ayala' },
  'עין הבשור':          { en: 'Ein HaBesor' },
  'עין הוד':            { en: 'Ein Hod' },
  'עין חצבה':           { en: 'Ein Hatzeva' },
  'עין יהב':            { en: 'Ein Yahav' },
  'עין יעקב':           { en: "Ein Ya'akov" },
  'עין כרם':            { en: 'Ein Karem' },
  'עין עירון':          { en: 'Ein Iron' },
  'עין שריד':           { en: 'Ein Sarid' },
  'עין תמר':            { en: 'Ein Tamar' },
  'עינת':               { en: 'Einat' },
  'עמינדב':             { en: 'Aminadav' },
  'עמיעד':              { en: "Ami'ad" },
  'עמיעוז':             { en: "Ami'oz" },
  'עמקה':               { en: 'Amka' },
  'ענב':                { en: 'Enav' },
  'עץ אפרים':           { en: 'Etz Efraim' },
  'עצמון שגב':          { en: 'Atzmon-Segev' },
  'עשרת':               { en: 'Aseret' },
  'עתניאל':             { en: "Otni'el" },
  'פארן':               { en: 'Paran' },
  'פדויים':             { en: 'Peduyim' },
  'פדיה':               { en: 'Pedaya' },
  'פורת':               { en: 'Porat' },
  'פטיש':               { en: 'Patish' },
  'פני חבר':            { en: 'Pene Hever' },
  'פסוטה':              { en: 'Fassuta' },
  'פרוד':               { en: 'Parod' },
  'פרזון':              { en: 'Perazon' },
  'פרי גן':             { en: 'Pri Gan' },
  'פתחיה':              { en: 'Petahya' },
  'צאלים':              { en: "Ze'elim" },
  'צביה':               { en: 'Tzvia' },
  'צובה':               { en: 'Tzova' },
  'צופיה':              { en: 'Tzofiya' },
  'צופית':              { en: 'Tzofit' },
  'צופר':               { en: 'Tzofar' },
  'צור משה':            { en: 'Tzur Moshe' },
  'צור נתן':            { en: 'Tzur Natan' },
  'צוריאל':             { en: 'Tzuriel' },
  'צורית':              { en: 'Tzurit' },
  'ציפורי':             { en: 'Zippori' },
  'צפריה':              { en: 'Tzafriya' },
  'צפרירים':            { en: 'Tzafririm' },
  'צרעה':               { en: "Tzor'a" },
  'קדמה':               { en: 'Kedma' },
  'קדרון':              { en: 'Kidron' },
  'קטורה':              { en: 'Ketura' },
  'קליה':               { en: 'Kalya' },
  'קמה':                { en: 'Kama' },
  'קציר':               { en: 'Katzir' },
  'קרית נטפים':         { en: 'Kiryat Netafim' },
  'קריית נטפים':        { en: 'Kiryat Netafim' },
  'קרית ענבים':         { en: 'Kiryat Anavim' },
  'קריית ענבים':        { en: 'Kiryat Anavim' },
  'קרית עקרון':         { en: 'Kiryat Ekron' },
  'קריית עקרון':        { en: 'Kiryat Ekron' },
  'קשת':                { en: 'Keshet' },
  'ראש צורים':          { en: 'Rosh Tzurim' },
  'רבבה':               { en: 'Revava' },
  'רבדים':              { en: 'Revadim' },
  'רגבה':               { en: 'Regba' },
  'רגבים':              { en: 'Regavim' },
  "רו'י":               { en: "Ro'i" },
  'רחוב':               { en: 'Rehov' },
  'רחלים':              { en: 'Rehelim' },
  'רימונים':            { en: 'Rimmonim' },
  'רינתיה':             { en: 'Rinatya' },
  'רמות':               { en: 'Ramot' },
  'רמות מאיר':          { en: 'Ramot Meir' },
  'רמות מנשה':          { en: 'Ramot Menashe' },
  'רמת הכובש':          { en: 'Ramat HaKovesh' },
  'רמת השופט':          { en: 'Ramat HaShofet' },
  'רמת ישי':            { en: 'Ramat Yishai' },
  'רמת צבי':            { en: 'Ramat Tzvi' },
  'רמת רזיאל':          { en: "Ramat Razi'el" },
  'רנן':                { en: 'Rannen' },
  'רקפת':               { en: 'Rakavet' },
  'רשפון':              { en: 'Rishpon' },
  'רשפים':              { en: 'Reshafim' },
  'רתמים':              { en: 'Retamim' },
  'שאר ישוב':           { en: "She'ar Yashuv" },
  'שבי דרום':           { en: 'Shave Darom' },
  'שבי ציון':           { en: 'Shave Zion' },
  'שבי שומרון':         { en: 'Shave Shomron' },
  'שדה אילן':           { en: 'Sde Ilan' },
  'שדה אליהו':          { en: 'Sde Eliyahu' },
  'שדה אליעזר':         { en: "Sde Eli'ezer" },
  'שדה בוקר':           { en: 'Sde Boker' },
  'שדה דוד':            { en: 'Sde David' },
  'שדה יואב':           { en: "Sde Yo'av" },
  'שדה יעקב':           { en: "Sde Ya'akov" },
  'שדה יצחק':           { en: 'Sde Yitzhak' },
  'שדה משה':            { en: 'Sde Moshe' },
  'שדה נחום':           { en: 'Sde Nahum' },
  'שדה נחמיה':          { en: 'Sde Nehemia' },
  'שדה ניצן':           { en: 'Sde Nitzan' },
  'שדה עוזיהו':         { en: 'Sde Uziyahu' },
  'שדה צבי':            { en: 'Sde Tzvi' },
  'שדות מיכה':          { en: 'Sdot Micha' },
  'שדי אברהם':          { en: 'Sdei Avraham' },
  'שדי חמד':            { en: 'Sdei Hemed' },
  'שדי תרומות':         { en: 'Sdei Trumot' },
  'שדמות דבורה':        { en: 'Shadmot Devora' },
  'שואבה':              { en: "Sho'eva" },
  'שובה':               { en: 'Shuva' },
  'שומרה':              { en: 'Shomera' },
  'שומריה':             { en: 'Shomeriya' },
  'שוקדה':              { en: 'Shokeda' },
  'שורש':               { en: 'Shoresh' },
  'שורשים':             { en: 'Shorashim' },
  'שזור':               { en: 'Shezor' },
  'שחר':                { en: 'Shahar' },
  'שיבולים':            { en: 'Shibolim' },
  'שילת':               { en: 'Shilat' },
  'שכניה':              { en: 'Shekhanya' },
  'שלוחות':             { en: 'Sheluhot' },
  'שמרת':               { en: 'Shamrat' },
  'שמשית':              { en: 'Shimshit' },
  'שפיר':               { en: 'Shafir' },
  'שקד':                { en: 'Shaked' },
  'שרונה':              { en: 'Sharona' },
  'שתולה':              { en: 'Shtula' },
  'שתולים':             { en: 'Shtulim' },
  'תובל':               { en: 'Tuval' },
  'תומר':               { en: 'Tomer' },
  'תימורים':            { en: 'Timmorim' },
  'תירוש':              { en: 'Tirosh' },
  'תל יצחק':            { en: 'Tel Yitzhak' },
  'תל עדשים':           { en: 'Tel Adashim' },
  'תלם':                { en: 'Telem' },
  'תלמי אליהו':         { en: 'Talmei Eliyahu' },
  'תלמי ביל"ו':         { en: 'Talmei Bilu' },
  'תלמי יוסף':          { en: 'Talmei Yosef' },
  'תלמי יחיאל':         { en: 'Talmei Yehiel' },
  'תלמי יפה':           { en: 'Talmei Yafe' },
  'תלמים':              { en: 'Telamim' },
  'תמרת':               { en: 'Timrat' },
  'תנובות':             { en: 'Tenuvot' },
  'תפרח':               { en: 'Tifrah' },
  'תקומה':              { en: 'Tekuma' },

  // ── Misc legacy / moshava ─────────────────────────────────────────────────────
  'כרמל':               { en: 'Karmel' },
  'מייסר':              { en: 'Meiser' },
  'דחי':                { en: 'Dahi' },
  'מושב':               { en: 'Moshav' },
  'קיבוץ':              { en: 'Kibbutz' },
  'אלון הגליל':         { en: 'Allon HaGalil' },
  'אלומות':             { en: 'Alummot' },
  'אלוני יצחק':         { en: 'Allone Yitzhak' },
  'אלונים':             { en: 'Allonim' },
  'אלמגור':             { en: 'Almagor' },
  'הזורעים':            { en: "HaZore'im" },
  'הסוללים':            { en: 'HaSolelim' },
  'העוגן':              { en: 'HaOgen' },
  "גת (קיבוץ)":         { en: 'Gat (Kibbutz)' },
  'קדמת צבי':           { en: 'Kidmat Tzvi' },
  'נס עמים':            { en: 'Nes Ammim' },
  'מאיר שפיה':          { en: "Me'ir Shfeya" },
  'לימן':               { en: 'Liman' },
  'גורנות הגליל':       { en: 'Gornot HaGalil' },
  'נוף צוף':            { en: 'Neve Tzuf' },
  'גבועות בר':          { en: "Geva'ot Bar" },
  'אמיר':               { en: 'Amir' },
  'כפר ביל"ו':          { en: 'Kfar Bilu' },
  'אשל הנשיא':          { en: 'Eshel HaNasi' },
  'ערוגות':             { en: 'Arugot' },
  'שדמות מחולה':        { en: 'Shadmot Mehola' },
  'כרם מהר"ל':          { en: 'Kerem Maharal' },
  'כרם בן שמן':         { en: 'Kerem Ben Shemen' },
  'גינתון':             { en: 'Ginneton' },
  'צנדלה':              { en: 'Sandala' },
  'ענבתא':              { en: 'Anabta' },
  'מוקייבלה':           { en: 'Mukeibila' },
  'נאעורה':             { en: "Na'ura" },
  'ניין':               { en: 'Nein' },
  'אל סייד':            { en: 'Al Sayyid' },
  'שדמה':               { en: 'Shdema' },
  'ברעם':               { en: "Bar'am" },
  'מסעודין אל-עזאזמה':  { en: "Mas'udin al-Azazme" },
  'ריחן':               { en: 'Reihan' },

  // ── More Gush Dan / Center ────────────────────────────────────────────────────
  'אבן ספיר':           { en: 'Even Sapir' },
  'בן שמן':             { en: 'Ben Shemen' },
  'גב ים':              { en: 'Gav Yam' },
  'גבעת אבני':          { en: 'Givat Avni' },
  'קדר':                { en: 'Kedar' },
  'קדרים':              { en: 'Kaddarim' },
  'עלי זהב':            { en: 'Ale Zahav' },
  'עלמון':              { en: 'Almon' },
  'פדואל':              { en: "Pedu'el" },
  'מגן שאול':           { en: 'Magen Shaul' },
  'גבעון החדשה':        { en: 'Givon HaHadasha' },
  'שומרון':             { en: 'Samaria' },
  'ברכה':               { en: 'Beracha' },
  'אלעזר':              { en: "El'azar" },
  // ── Auto-appended by scripts/add_city_translations.py ────────────────────
  'אביאל': { en: "Aviel", ru: "Авиэль", ar: "أفيئيل", fr: "Aviel" },
  'אביעזר': { en: "Aviezer", ru: "Авиэзер", ar: "أفيعزر", fr: "Aviezer" },
  'אדרת': { en: "Aderet", ru: "Адерет", ar: "أديريت", fr: "Aderet" },
  'אודים': { en: "Udim", ru: "Удим", ar: "أوديم", fr: "Udim" },
  'אומץ': { en: "Ometz", ru: "Омец", ar: "أوميتس", fr: "Ometz" },
  'אורה': { en: "Ora", ru: "Ора", ar: "أورا", fr: "Ora" },
  'אושה': { en: "Usha", ru: "Уша", ar: "أوشا", fr: "Usha" },
  'אחיהוד': { en: "Ahihud", ru: "Ахихуд", ar: "أحيهود", fr: "Ahihud" },
  'אירוס': { en: "Iris", ru: "Ирис", ar: "إيريس", fr: "Iris" },
  'אפק': { en: "Afek", ru: "Афек", ar: "أفيك", fr: "Afek" },
  'ארסוף': { en: "Arsuf", ru: "Арсуф", ar: "أرسوف", fr: "Arsuf" },
  'אשרת': { en: "Asheret", ru: "Ашерет", ar: "أشيريت", fr: "Asheret" },
  'אשתאול': { en: "Eshtaol", ru: "Эштаоль", ar: "إشتاؤول", fr: "Eshtaol" },
  'בית חרות': { en: "Beit Herut", ru: "Бейт-Херут", ar: "بيت حيروت", fr: "Beit Herut" },
  'בית חשמונאי': { en: "Beit Hashmonai", ru: "Бейт-Хашмонай", ar: "بيت حشمونائي", fr: "Beit Hashmonai" },
  'בית יצחק שער חפר': { en: "Beit Yitzhak-Sha'ar Hefer", ru: "Бейт-Ицхак", ar: "بيت يتسحاق", fr: "Beit Yitzhak" },
  'בית נקופה': { en: "Beit Nekofa", ru: "Бейт-Некофа", ar: "بيت نقوفا", fr: "Beit Nekofa" },
  'בית עוזיאל': { en: "Beit Uziel", ru: "Бейт-Узиэль", ar: "بيت عوزيئيل", fr: "Beit Uziel" },
  'בצרה': { en: "Bazra", ru: "Бацра", ar: "بصرة", fr: "Bazra" },
  'בצת': { en: "Betzet", ru: "Бецет", ar: "بيتسيت", fr: "Betzet" },
  "ג'סר א זרקא": { en: "Jisr az-Zarqa", ru: "Джиср аз-Зарка", ar: "جسر الزرقاء", fr: "Jisr az-Zarqa" },
  'גבעת יערים': { en: "Givat Ye'arim", ru: "Гиват-Йеарим", ar: "غيفعات يعاريم", fr: "Givat Ye'arim" },
  'גת רימון': { en: "Gat Rimon", ru: "Гат-Римон", ar: "غات ريمون", fr: "Gat Rimon" },
  'החותרים': { en: "HaHoterim", ru: "ХаХотерим", ar: "هاحوتريم", fr: "HaHoterim" },
  'חופית': { en: "Hofit", ru: "Хофит", ar: "حوفيت", fr: "Hofit" },
  'חרוצים': { en: "Harutzim", ru: "Харуцим", ar: "حروتسيم", fr: "Harutzim" },
  'טירת יהודה': { en: "Tirat Yehuda", ru: "Тират-Йехуда", ar: "طيرة يهودا", fr: "Tirat Yehuda" },
  'יגל': { en: "Yagel", ru: "Ягель", ar: "ياغيل", fr: "Yagel" },
  'יד רמב"ם': { en: "Yad Rambam", ru: "Яд-Рамбам", ar: "ياد رمبام", fr: "Yad Rambam" },
  'יהוד מונוסון': { en: "Yehud-Monosson", ru: "Йехуд-Моноссон", ar: "يهود-مونوسون", fr: "Yehud-Monosson" },
  'ינוב': { en: "Yanuv", ru: "Янув", ar: "يانوف", fr: "Yanuv" },
  'יסעור': { en: "Yas'ur", ru: "Ясур", ar: "ياسعور", fr: "Yas'ur" },
  'יעף': { en: "Ya'af", ru: "Яаф", ar: "ياعاف", fr: "Ya'af" },
  'יקנעם (מושבה)': { en: "Yokneam Moshava", ru: "Йокнеам-Мошава", ar: "يوكنعام موشافا", fr: "Yokneam Moshava" },
  'ישרש': { en: "Yashresh", ru: "Яшреш", ar: "يشريش", fr: "Yashresh" },
  'כוכב יאיר / צור יגאל': { en: "Kokhav Yair-Tzur Yigal", ru: "Кохав-Яир", ar: "كوخاف يائير", fr: "Kokhav Yair" },
  'כסלון': { en: "Ksalon", ru: "Кесалон", ar: "كيسالون", fr: "Ksalon" },
  'כפר הנגיד': { en: "Kfar HaNagid", ru: "Кфар-Ха-Нагид", ar: "كفار هنغيد", fr: "Kfar HaNagid" },
  'כפר הרא"ה': { en: "Kfar HaRoeh", ru: "Кфар-ХаРоэ", ar: "كفار هارواه", fr: "Kfar HaRoeh" },
  'כפר יעבץ': { en: "Kfar Yavetz", ru: "Кфар-Явец", ar: "كفار يعبيتس", fr: "Kfar Yavetz" },
  'מוצא עילית': { en: "Motza Illit", ru: "Моца-Илит", ar: "موتسا عيليت", fr: "Motza Illit" },
  'מכמורת': { en: "Mikhmoret", ru: "Михморет", ar: "مخموريت", fr: "Mikhmoret" },
  'עולש': { en: "Olesh", ru: "Олеш", ar: "عوليش", fr: "Olesh" },
  'פרדס חנה כרכור': { en: "Pardes Hanna-Karkur", ru: "Пардес-Ханна-Каркур", ar: "برديس حنا-كركور", fr: "Pardes Hanna-Karkur" },
  'צוקי ים': { en: "Tzukei Yam", ru: "Цукей-Ям", ar: "تسوكي يام", fr: "Tzukei Yam" },
  'קדימה צורן': { en: "Kadima-Tzoran", ru: "Кадима-Цоран", ar: "قاديما-تسوران", fr: "Kadima-Tzoran" },
  'קרית גת': { en: "Kiryat Gat", ru: "Кирьят-Гат", ar: "كريات غات", fr: "Kiryat Gat" },
  'שדה ורבורג': { en: "Sde Warburg", ru: "Сде-Варбург", ar: "سديه وربورغ", fr: "Sde Warburg" },
  'שושנת העמקים': { en: "Shoshanat HaAmakim", ru: "Шошанат-ха-Амаким", ar: "شوشانات هعماكيم", fr: "Shoshanat HaAmakim" },
  'שעלבים': { en: "Sha'alvim", ru: "Шаалвим", ar: "شعلفيم", fr: "Sha'alvim" },
  'שער אפרים': { en: "Sha'ar Efrayim", ru: "Шаар-Эфраим", ar: "شاعار إفرايم", fr: "Sha'ar Efrayim" },
  'שריגים': { en: "Srigim", ru: "Сригим", ar: "سريغيم", fr: "Srigim" },
  'תלמי אלעזר': { en: "Talmei Elazar", ru: "Талмей-Элазар", ar: "تلمي العزار", fr: "Talmei Elazar" },
  // ── CBS full locality list (data.gov.il) ─ auto-added for consistent display ──
  "אבו ג'ווייעד (שבט)": { en: "Abu Juwei'id", ar: "أبو جويعد" },
  "אבו סריחאן (שבט)": { en: "Abu Sureihan", ar: "أبو سريحان" },
  "אבו עבדון (שבט)": { en: "Abu Abdun", ar: "أبو عبدون" },
  "אבו עמאר (שבט)": { en: "Abu Ammar", ar: "أبو عمار" },
  "אבו עמרה (שבט)": { en: "Abu Amre", ar: "أبو عمرة" },
  "אבו קורינאת (שבט)": { en: "Abu Qureinat", ar: "أبو قرينات" },
  "אבו קרינאת (יישוב)": { en: "Abu Qureinat", ar: "أبو قرينات" },
  "אבו רובייעה (שבט)": { en: "Abu Rubei'a", ar: "أبو ربيعة" },
  "אבו רוקייק (שבט)": { en: "Abu Ruqayyeq", ar: "أبو رقيق" },
  "אבו תלול": { en: "Abu Tulul", ar: "أبو تلول" },
  "אבטין": { en: "Ibtin", ar: "إبطن" },
  "אבטליון": { en: "Avtalyon", ar: "أڤتَليون" },
  "אביבים": { en: "Avivim", ar: "أڤيڤيم", ru: "Авивим" },
  "אבירים": { en: "Abbirim", ar: "أبيريم", ru: "Абирим" },
  "אבן מנחם": { en: "Even Menahem", ar: "إيڤِن مِنَحيم", ru: "Эвен Менахем" },
  "אבני איתן": { en: "Avne Etan", ar: "أڤني إيتان", ru: "Авне Этан" },
  "אבני חפץ": { en: "Avne Hefez", ar: "أڤني حيفِتس" },
  "אבנת": { en: "Avenat", ar: "أڤنات", ru: "Авенат" },
  "אבשלום": { en: "Avshalom", ar: "أڤشَلوم", ru: "Авшалом" },
  "אדורה": { en: "Adora", ar: "أدورا", ru: "Адора" },
  "אדירים": { en: "Addirim", ar: "أديريم", ru: "Аддирим" },
  "אדמית": { en: "Adamit", ar: "أدَميت", ru: "Адамит" },
  "אודם": { en: "Odem", ar: "أودِم" },
  "אוהד": { en: "Ohad", ar: "أوهَد" },
  "אום אל-קוטוף": { en: "Umm Al-qutuf", ar: "أم القطف" },
  "אום בטין": { en: "Umm Batin", ar: "أم بطين" },
  "אומן": { en: "Omen", ar: "أومِن" },
  "אור הגנוז": { en: "Or Haganuz", ar: "أور هچَنوز" },
  "אורות": { en: "Orot", ar: "أوروت" },
  "אורים": { en: "Urim", ar: "أوريم", ru: "Урим" },
  "אורנים": { en: "Oranim", ar: "أُرَنيم" },
  "אחווה": { en: "Ahawa", ar: "أحَڤا", ru: "Ахава" },
  "אחוזם": { en: "Ahuzzam", ar: "أحُزام", ru: "Ахуззам" },
  "אחוזת ברק": { en: "Ahuzzat Baraq", ar: "أحُزات بَراك", ru: "Ахузат Барак" },
  "אטרש (שבט)": { en: "Atrash", ar: "أطرش" },
  "אייל": { en: "Eyal", ar: "إيال", ru: "Эяль" },
  "אילון": { en: "Elon", ar: "إيلون" },
  "אילות": { en: "Elot", ar: "إيلوت" },
  "איתמר": { en: "Itamar", ar: "إيتمار", ru: "Итамар" },
  "איתן": { en: "Etan", ar: "إيتان" },
  "איתנים": { en: "Etanim", ar: "إيتَنيم" },
  "אל-עזי": { en: "Al-azy", ar: "العزي" },
  "אל-עריאן": { en: "Al-aryan", ar: "العريان" },
  "אלומה": { en: "Alumma", ar: "ألُما" },
  "אלוני הבשן": { en: "Allone Habashan", ar: "ألوني هبشان" },
  "אלי-עד": { en: "Eli Al", ar: "إلي عاد" },
  "אליאב": { en: "Eliav", ar: "إليآڤ" },
  "אליפז": { en: "Elifaz", ar: "إليفاز", ru: "Элифаз" },
  "אליפלט": { en: "Elifelet", ar: "إليفيلِت" },
  "אלישמע": { en: "Elishama", ar: "إليشَماع", ru: "Элишама" },
  "אלמוג": { en: "Almog", ar: "ألموچ", ru: "Альмог" },
  "אלקוש": { en: "Elqosh", ar: "إلكوش" },
  "אלקנה": { en: "Elqana", ar: "إلكنا", ru: "Элькана" },
  "אמנון": { en: "Amnun", ar: "أمنون" },
  "אניעם": { en: "Ani'am", ar: "أنيعام" },
  "אסד (שבט)": { en: "Asad", ar: "أسد" },
  "אספר": { en: "Asefar", ar: "أسفار" },
  "אעבלין": { en: "I'billin", ar: "إعبلين" },
  "אעצם (שבט)": { en: "A'sam", ar: "أعصم" },
  "אפיניש (שבט)": { en: "Afeinish", ar: "أفينش" },
  "ארבל": { en: "Arbel", ar: "أربيل" },
  "אשבל": { en: "Nahal Eshbal", ar: "إشبال" },
  "אשדות יעקב (איחוד)": { en: "Ashdot Ya'aqov(ihud)", ar: "أشدوت يعكوڤ (إحود)" },
  "אשדות יעקב (מאוחד)": { en: "Ashdot Ya'aqov(me'uh", ar: "أشدوت يعكوڤ (مِؤُحاد)" },
  "אשחר": { en: "Eshhar", ar: "إشحار" },
  "אשלים": { en: "Ashalim", ar: "أشليم" },
  "אתגר": { en: "Etgar", ar: "اتجار" },
  "באר אורה": { en: "Be'er Ora", ar: "بِئير أورا" },
  "באר גנים": { en: "Beer Gannim", ar: "بِئير چنيم" },
  "באר מילכה": { en: "Be'er Milka", ar: "بِئير مِلكا" },
  "בטחה": { en: "Bitha", ar: "بِتحا" },
  "ביצרון": { en: "Bizzaron", ar: "بِتسَرون", ru: "Бизарон" },
  "ביר הדאג'": { en: "Bir Hadage", ar: "بئر هداج", ru: "Бир-Хададж" },
  "ביריה": { en: "Biriyya", ar: "بيريا" },
  "בית ברל": { en: "Bet Berl", ar: "بيت بيرل" },
  "בית הגדי": { en: "Bet Hagaddi", ar: "بيت هچَدي" },
  "בית רבן": { en: "Bet Rabban", ar: "بيت رَبان" },
  "בית רימון": { en: "Bet Rimmon", ar: "بيت رِمون" },
  "בן שמן (כפר נוער)": { en: "Ben Shemen(k.no'ar)", ar: "بين شيمِن", ru: "Бен-Ше́мен (молодёжная деревня)" },
  "בן שמן (מושב)": { en: "Ben Shemen (moshav)", ar: "بين شيمِن", ru: "Бен-Ше́мен" },
  "בני דקלים": { en: "Bne Dkalim", ar: "بني دكليم" },
  "בני נצרים": { en: "Bene Nezarim", ar: "بني نِتَسريم" },
  "בני עי\"ש": { en: "Bene Ayish", ar: "بني عايِش", ru: "Бней-Айш" },
  "בניה": { en: "Benaya", ar: "بْنَيا", ru: "Бная" },
  "בסמ\"ה": { en: "Basma", ar: "بسمة", ru: "Басма" },
  "בקוע": { en: "Beqoa", ar: "بكووَع" },
  "בקעות": { en: "Beqa'ot", ar: "بِكَعوت" },
  "בר גיורא": { en: "Bar Giyyora", ar: "بار چيورا" },
  "בר יוחאי": { en: "Bar Yohay", ar: "بار يوحاي" },
  "ברוש": { en: "Berosh", ar: "بْروش" },
  "ברק": { en: "Baraq", ar: "براك", ru: "Барак" },
  "בת הדר": { en: "Bat Hadar", ar: "بات هَدار" },
  "בת עין": { en: "Bat Ayin", ar: "بات عايِن" },
  "ג'וליס": { en: "Julis", ar: "جولس", ru: "Джулис" },
  "ג'נאביב (שבט)": { en: "Junnabib", ar: "جلجولية" },
  "ג'ש (גוש חלב)": { en: "Jish(gush Halav)", ar: "الجش (چوش حَلاڤ)", ru: "Джиш (Гуш Халав)" },
  "גבולות": { en: "Gevulot", ar: "چڤولوت" },
  "גבע כרמל": { en: "Geva Karmel", ar: "چيڤع كرميل" },
  "גבעולים": { en: "Giv'olim", ar: "چِڤعوليم" },
  "גבעות בר": { en: "Geva'ot Bar", ar: "چِڤعوت بار" },
  "גבעות עדן": { en: "Giv'ot Eden", ar: "چِڤعوت عيدِن" },
  "גבעת חיים (איחוד)": { en: "Giv'at Hayyim (ihud)", ar: "چِڤعات حَييم (إحود)" },
  "גבעת חיים (מאוחד)": { en: "Giv'at Hayyim(me'uha", ar: "چِڤعات حَييم (مِؤُحاد)" },
  "גבעת כ\"ח": { en: "Giv'at Koah", ar: "چِڤعات كووَح" },
  "גבעת ניל\"י": { en: "Giv'at Nili", ar: "چِڤعات نيلي" },
  "גבעת שמש": { en: "Giv'at Shemesh", ar: "چِڤعات شيمِش" },
  "גבעת שפירא": { en: "Giv'at Shappira", ar: "چِڤعات شَپيرا" },
  "גבעתי": { en: "Giv'ati", ar: "چِڤعتي" },
  "גדעונה": { en: "Gid'ona", ar: "چِدعونا" },
  "גונן": { en: "Gonen", ar: "چونين" },
  "גלגל": { en: "Gilgal", ar: "چِلچال" },
  "גלעד (אבן יצחק)": { en: "Even Yizhaq(gal'ed)", ar: "چَلعيد (إيڤِن يِتسحاك)" },
  "גני מודיעין": { en: "Ganne Modiin", ar: "چَني موديعين" },
  "געש": { en: "Ga'ash", ar: "چاعَش" },
  "געתון": { en: "Ga'ton", ar: "چَعتون" },
  "גרופית": { en: "Gerofit", ar: "چروفيت" },
  "גשור": { en: "Geshur", ar: "چِشور" },
  "דביר": { en: "Dvir", ar: "دڤير" },
  "דוב\"ב": { en: "Dovev", ar: "دوڤيڤ" },
  "דור": { en: "Dor", ar: "دور" },
  "דייר אל-אסד": { en: "Deir Al-asad", ar: "ديمونا", ru: "Дейр-аль-Асад" },
  "דייר ראפאת": { en: "Deir Rafat", ar: "دير حنا" },
  "דמיידה": { en: "Demeide", ar: "ضميدة" },
  "דקל": { en: "Deqel", ar: "ديكِل", ru: "Декель" },
  "דריג'את": { en: "Derig'at", ar: "دريجات", ru: "Дриджат" },
  "הוואשלה (שבט)": { en: "Hawashla", ar: "الهواشلة" },
  "הוזייל (שבט)": { en: "Huzayyel", ar: "هوشعيا" },
  "הילה": { en: "Hilla", ar: "هِلا" },
  "המעפיל": { en: "Hama'pil", ar: "همَعپيل" },
  "הרדוף": { en: "Harduf", ar: "هردوف" },
  "ורדון": { en: "Wardon", ar: "ڤردون" },
  "זבארגה (שבט)": { en: "Zabarga", ar: "الزبارقة" },
  "זבדיאל": { en: "Zavdi'el", ar: "زَڤديئيل" },
  "זנוח": { en: "Zanoah", ar: "زنووَح" },
  "זרועה": { en: "Zeru'a", ar: "زروعا" },
  "זרחיה": { en: "Zerahya", ar: "زِرَحيا" },
  "ח'ואלד (שבט)": { en: "Khawaled", ar: "خوالد" },
  "חבר": { en: "Hever", ar: "حيڤِر" },
  "חברון": { en: "Hebron", ar: "الخليل" },
  "חגי": { en: "Haggai", ar: "حَچاي" },
  "חד-נס": { en: "Had-nes", ar: "حاد نيس" },
  "חוג'ייראת (ד'הרה)": { en: "Hujeirat (dahra)", ar: "حُچلا" },
  "חולית": { en: "Holit", ar: "حوليت" },
  "חולתה": { en: "Hulata", ar: "حولاتا" },
  "חוסנייה": { en: "Hussniyya", ar: "الحسنية" },
  "חוקוק": { en: "Huqoq", ar: "حوكوك" },
  "חורשים": { en: "Horeshim", ar: "حورشيم", ru: "Хоршим" },
  "חזון": { en: "Hazon", ar: "حَزون" },
  "חיננית": { en: "Hinnanit", ar: "حِنَنيت" },
  "חלוץ": { en: "Haluz", ar: "حَلوتس" },
  "חמאם": { en: "Hamam", ar: "حمام" },
  "חמדת": { en: "Nahal Hemdat", ar: "حِمدات" },
  "חספין": { en: "Haspin", ar: "حِسپين" },
  "חצור-אשדוד": { en: "Hazor-ashdod", ar: "حتْسور (أشدود)" },
  "חצרים": { en: "Hazerim", ar: "حتْسِريم", ru: "Хацерим" },
  "חרשים": { en: "Harashim", ar: "حَرَشيم" },
  "טייבה (בעמק)": { en: "Tayibe(baemeq)", ar: "الطيبة الزعبية" },
  "טללים": { en: "Telalim", ar: "تْلَليم" },
  "טמרה (יזרעאל)": { en: "Tamra (yizre'el)", ar: "طمرة الزعبية" },
  "טנא": { en: "Tene", ar: "تيني" },
  "טפחות": { en: "Tefahot", ar: "تْفَحوت" },
  "יבול": { en: "Yevul", ar: "يِڤول" },
  "יד השמונה": { en: "Yad Hashemona", ar: "ياد هشمونا", ru: "ЯД АШЕМОНА" },
  "ידידה": { en: "Yedida", ar: "يِديدا" },
  "יושיביה": { en: "Yoshivya", ar: "يوشيڤْيا" },
  "ייט\"ב": { en: "Yitav", ar: "يِيتاڤ" },
  "יעל": { en: "Ya'el", ar: "ياعيل" },
  "יפתח": { en: "Yiftah", ar: "يِفتاح" },
  "יקיר": { en: "Yaqir", ar: "يَكير" },
  "ירדנה": { en: "Yardena", ar: "يرْدينا" },
  "ישע": { en: "Yesha", ar: "يِيشع" },
  "ישעי": { en: "Yish'i", ar: "يِشْعي" },
  "כדורי": { en: "Kadoorie", ar: "كَدوري" },
  "כורזים": { en: "Korazim", ar: "كورَزيم" },
  "כחל": { en: "Kahal", ar: "كَحال" },
  "כחלה": { en: "Kochlea", ar: "كحلة" },
  "כישור": { en: "Kishor", ar: "كيشور" },
  "כליל": { en: "Kelil", ar: "كْليل" },
  "כלנית": { en: "Kallanit", ar: "كلنيت" },
  "כמאנה": { en: "Kammana", ar: "الكمانة" },
  "כמהין": { en: "Kemehin", ar: "كْمِهين" },
  "כמון": { en: "Kammon", ar: "كَمون" },
  "כנות": { en: "Kannot", ar: "كَنوت" },
  "כנף": { en: "Kanaf", ar: "كَناف" },
  "כנרת (מושבה)": { en: "Kinneret(moshava)", ar: "كِنيرِت (موشَڤا)", ru: "Кинерет (мошава)" },
  "כנרת (קבוצה)": { en: "Kinneret(qevuza)", ar: "كِنيرِت (كڤوتسا)", ru: "Квуцат-Кинерет" },
  "כעביה-טבאש-חג'אג'רה": { en: "Ka'abiyye-tabbash-ha", ar: "كعبية–طباش–حجاجرة" },
  "כפר ברא": { en: "Kafar Bara", ar: "كفر برا" },
  "כפר האורנים": { en: "Kefar Haoranim", ar: "كفار هَؤُرَنيم" },
  "כפר הנוער הדתי": { en: "Kefar Hano'ar Hadati", ar: "كفار هنوعر هدَتي" },
  "כפר הרי\"ף": { en: "Kefar Harif", ar: "كفار هريف" },
  "כפר זוהרים": { en: "Kefar Zoharim", ar: "كفار زوهريم" },
  "כפר חסידים א'": { en: "Kefar Hasidim Alef", ar: "كفار حسيديم ألف" },
  "כפר חסידים ב'": { en: "Kefar Hasidim Bet", ar: "كفار حسيديم بيت" },
  "כפר מל\"ל": { en: "Kefar Malal", ar: "كفر مصر" },
  "כפר סילבר": { en: "Kefar Silver", ar: "كفار سيلڤِر" },
  "כפר עבודה": { en: "Kefar Avoda", ar: "كفار عڤودا" },
  "כפר רוזנואלד (זרעית)": { en: "Kefar Rozenwald(zar.", ar: "كفار روزِنڤلد (زرعيت)" },
  "כרי דשא": { en: "Kare Deshe", ar: "كفار تپووَح" },
  "כרם ביבנה (ישיבה)": { en: "Kerem Beyavne", ar: "كيرِم بِيَڤني (يِشيڤا)" },
  "כרמי קטיף": { en: "Karme Qatif", ar: "كرمي كَتيف" },
  "כרמים": { en: "Keramim", ar: "كرَميم" },
  "לכיש": { en: "Lakhish", ar: "لخيش" },
  "לפידות": { en: "Lappidot", ar: "لپيدوت" },
  "מבואות ים": { en: "Mevo'ot Yam", ar: "مِڤوؤوت يام" },
  "מבואות יריחו": { en: "Mevo'ot Yeriho", ar: "مِڤوؤوت يريهو" },
  "מבקיעים": { en: "Mavqi'im", ar: "مڤكيعيم" },
  "מג'דל שמס": { en: "Majdal Shams", ar: "مجدل شمس", ru: "Мадждаль-Шамс" },
  "מגדלים": { en: "Migdalim", ar: "مِچدليم" },
  "מדרך עוז": { en: "Midrakh Oz", ar: "مِدراخ عوز" },
  "מדרשת בן גוריון": { en: "Midreshet Ben Gurion", ar: "مِدريشِت بين چوريون" },
  "מדרשת רופין": { en: "Midreshet Ruppin", ar: "مِدريشِت روپين" },
  "מזרעה": { en: "Mazra'a", ar: "المزرعة" },
  "מחסיה": { en: "Mahseya", ar: "مَحسِيا" },
  "מיטב": { en: "Metav", ar: "ميتاڤ" },
  "מיטל": { en: "Metal", ar: "ميتال" },
  "מיצר": { en: "Mezar", ar: "مِتْسار" },
  "מירב": { en: "Merav", ar: "مِراڤ" },
  "מישר": { en: "Meshar", ar: "ميشار" },
  "מכחול": { en: "Makchul", ar: "مكحول" },
  "מכמנים": { en: "Mikhmannim", ar: "مِخْمَنيم" },
  "מנשית זבדה": { en: "Manshiyyet Zabda", ar: "منشية الزبدة" },
  "מעגלים": { en: "Ma'galim", ar: "معچليم" },
  "מעלה עירון": { en: "Ma'ale Iron", ar: "طلعة عارة (مَعلي عيرون)" },
  "מצדות יהודה": { en: "Mezadot Yehuda", ar: "مِتْسَدوت يِهودا" },
  "מצפה": { en: "Mizpa", ar: "مِتْسپا" },
  "מקווה ישראל": { en: "Miqwe Yisra'el", ar: "مِكْڤي يِسرَئيل", ru: "Микве Исраэль" },
  "מרחב עם": { en: "Merhav Am", ar: "مِرحاڤ عام" },
  "מרחביה (מושב)": { en: "Merhavya(moshav)", ar: "مِرحَڤيا (موشاڤ)" },
  "מרחביה (קיבוץ)": { en: "Merhavya(qibbuz)", ar: "مِرحَڤيا (كِبوتس)" },
  "משגב דב": { en: "Misgav Dov", ar: "مِسچاڤ دوڤ" },
  "משען": { en: "Mash'en", ar: "مَشعين" },
  "נאות סמדר": { en: "Shizzafon", ar: "نِؤوت سْـمَدار" },
  "נוה צוף": { en: "Neve Tsuf", ar: "نِڤي تسوف" },
  "נווה": { en: "Nave", ar: "نَڤي" },
  "נווה אבות": { en: "Newe Avot", ar: "نِڤي أڤوت" },
  "נווה חריף": { en: "Newe Harif", ar: "نِڤي حَريف" },
  "נווה מבטח": { en: "Newe Mivtah", ar: "نِڤي مِڤتاح" },
  "נופך": { en: "Nofekh", ar: "نوفِخ" },
  "נוקדים": { en: "Noqedim", ar: "نوكديم" },
  "נחליאל": { en: "Nahali'el", ar: "نحَليئيل" },
  "נטור": { en: "Natur", ar: "نَتور" },
  "נטע": { en: "Neta", ar: "نيتع" },
  "ניצן ב'": { en: "Nizzan B", ar: "نِتْسان بيت" },
  "ניצנה (קהילת חינוך)": { en: "Nizzana (qehilat Hin", ar: "نِتْسانا" },
  "ניצני סיני": { en: "Nizzane Sinay", ar: "نِتْسَني سيناي" },
  "ניר דוד (תל עמל)": { en: "Nir Dawid (tel Amal)", ar: "تيل عَمال (نير دَڤيد)" },
  "ניר ח\"ן": { en: "Nir Hen", ar: "نير حين" },
  "נעורים": { en: "Ne'urim", ar: "نِعوريم" },
  "נעלה": { en: "Na'ale", ar: "نَعَلي" },
  "נעמ\"ה": { en: "Naama", ar: "نَعَما" },
  "נען": { en: "Na'an", ar: "ناعَن" },
  "נערן": { en: "Na'aran", ar: "نَعَران" },
  "נצאצרה (שבט)": { en: "Nasasra", ar: "النصاصرة" },
  "סאג'ור": { en: "Sajur", ar: "ساجور" },
  "סואעד (חמרייה)": { en: "Sawa'id(hamriyye)", ar: "سواعد (حميرة)" },
  "סואעד (כמאנה) (שבט)": { en: "Sawa'id (kamane)", ar: "سواعد (كمانة)" },
  "סולם": { en: "Sulam", ar: "سولم" },
  "סוסיה": { en: "Suseya", ar: "سوسيا" },
  "סייד (שבט)": { en: "Sayyid", ar: "سيد" },
  "סלמה": { en: "Sallama", ar: "سلامة" },
  "סלעית": { en: "Sal'it", ar: "سلعيت" },
  "סנסנה": { en: "Sansanna", ar: "سنْسنا" },
  "סעוה": { en: "Sa'wa", ar: "سعوة" },
  "עגור": { en: "Agur", ar: "عَچور" },
  "עדנים": { en: "Adanim", ar: "عَدَنيم" },
  "עוזה": { en: "Uza", ar: "عُزا" },
  "עוזייר": { en: "Uzeir" },
  "עופר": { en: "Ofer", ar: "عوفِر" },
  "עוקבי (בנו עוקבה)": { en: "Uqbi (banu Uqba)", ar: "العقبي (بنو عقبة)" },
  "עזוז": { en: "Ezuz", ar: "عِزوز" },
  "עזר": { en: "Ezer", ar: "عيزِر" },
  "עטאוונה (שבט)": { en: "Atawne", ar: "العطاونة" },
  "עין אל-אסד": { en: "Ein Al-asad", ar: "عين الأسد" },
  "עין העמק": { en: "En Haemeq", ar: "عين هعيمِك" },
  "עין השלושה": { en: "En Hashelosha", ar: "عين هشْلوشا" },
  "עין חוד": { en: "Ein Hod", ar: "عين حوض" },
  "עין חרוד (איחוד)": { en: "En Harod (ihud)", ar: "عين حَرود (إحود)" },
  "עין חרוד (מאוחד)": { en: "En Harod(me'uhad)", ar: "عين حَرود (مِؤُحاد)" },
  "עין כרם-בי\"ס חקלאי": { en: "En Karem-b.s.haqla'i", ar: "عين كيرِم (مدرسة زراعية)" },
  "עין נקובא": { en: "Ein Naqquba", ar: "عين نقوبا" },
  "עין קנייא": { en: "Ein Qiniyye", ar: "عين قنية" },
  "עין ראפה": { en: "Ein Rafa", ar: "عين رافة" },
  "עיר אובות": { en: "Ir Ovot", ar: "عير أوڤوت" },
  "עלומים": { en: "Alumim", ar: "علوميم" },
  "עלמה": { en: "Alma", ar: "علما" },
  "עמוקה": { en: "Amuqqa", ar: "عَمُكا" },
  "עמיחי": { en: "Ammihay", ar: "عميحاي" },
  "עמיר": { en: "Amir", ar: "عمير" },
  "עראמשה": { en: "Aramsha", ar: "عرامشة" },
  "ערב אל נעים": { en: "Arrab Al Naim", ar: "عرب النعيم" },
  "פוריה - כפר עבודה": { en: "Poriyya-kefar Avoda", ar: "پورِيا (كفار عڤودا)" },
  "פוריה - נווה עובד": { en: "Poriyya-newe Oved", ar: "پورِيا (نِڤي عوڤيد)" },
  "פוריה עילית": { en: "Poriyya Illit", ar: "پورِيا عِليت" },
  "פלך": { en: "Pelekh", ar: "پيلِخ" },
  "פעמי תש\"ז": { en: "Pa'ame Tashaz", ar: "پَعَمي تَشاز" },
  "פצאל": { en: "Peza'el", ar: "پِتْسَئيل" },
  "פקיעין חדשה": { en: "Peqi'in Hadasha", ar: "پكيعين هحدشا" },
  "צבעון": { en: "Ziv'on", ar: "تسفعون" },
  "צוחר": { en: "Zohar", ar: "تسوحر" },
  "צופים": { en: "Zufin", ar: "تْسوفيم" },
  "צוקים": { en: "Mahane Bildad", ar: "تْسوكيم" },
  "צלפון": { en: "Zelafon", ar: "تْسلَفون" },
  "צרופה": { en: "Zerufa", ar: "تْسروفا" },
  "קבועה (שבט)": { en: "Qabbo'a", ar: "قبوعة" },
  "קודייראת א-צאנע(שבט)": { en: "Qudeirat As-sani", ar: "قديرات الصانع" },
  "קוואעין (שבט)": { en: "Qawa'in", ar: "قواعين" },
  "קוממיות": { en: "Qomemiyyut", ar: "كومِمِيوت" },
  "קורנית": { en: "Qoranit", ar: "كورَنيت" },
  "קלחים": { en: "Qelahim", ar: "كْلَحيم" },
  "קלע": { en: "Qela", ar: "كيلع" },
  "קצר א-סר": { en: "Kasr As-sirr", ar: "قصر السر" },
  "קרית שלמה": { en: "Qiryat Shelomo", ar: "كِريات شلُمو", ru: "Кирьят Шломо" },
  "ראס אל-עין": { en: "Ras Al-ein", ar: "رأس العين" },
  "ראס עלי": { en: "Ras Ali", ar: "رأس علي" },
  "רביד": { en: "Ravid", ar: "رَڤيد" },
  "רווחה": { en: "Rewaha", ar: "رِڤَحا" },
  "רוויה": { en: "Rewaya", ar: "رِڤَيا" },
  "רוח מדבר": { en: "Ruah Midbar", ar: "رووَح مِدبار" },
  "רומאנה": { en: "Rummane", ar: "رمانة" },
  "רומת הייב": { en: "Rumat Heib", ar: "رمة الهيب" },
  "רועי": { en: "Ro'i", ar: "روعي" },
  "רותם": { en: "Rotem", ar: "روتيم" },
  "רם-און": { en: "Ram-on", ar: "رام أون" },
  "רמת טראמפ": { en: "Trump Heights", ar: "رَمات ترامپ" },
  "שבלי - אום אל-גנם": { en: "Shibli", ar: "الشبلي – أم الغنم" },
  "שחרות": { en: "Shaharut", ar: "شَحَروت" },
  "שיזף": { en: "Shezaf", ar: "شزاف" },
  "שיטים": { en: "Nahal Shittim", ar: "شيتيم" },
  "שייח' דנון": { en: "Sheikh Dannun", ar: "الشيخ دنون" },
  "שלווה": { en: "Shalwa", ar: "شَلڤا" },
  "שלומית": { en: "Shlomit", ar: "شلوميت" },
  "שמעה": { en: "Shim'a", ar: "شِمعا" },
  "שני": { en: "Shani", ar: "شَني" },
  "שעל": { en: "Sha'al", ar: "شاعَل" },
  "שער הגולן": { en: "Sha'ar Hagolan", ar: "شاعَر هچولان" },
  "שער העמקים": { en: "Sha'ar Haamaqim", ar: "شاعَر هعمكيم" },
  "שער מנשה": { en: "Sha'ar Menashe", ar: "شاعَر مِنَشي" },
  "שער שומרון": { en: "Sha'ar Shomron", ar: "شاعر شمرون" },
  "שפר": { en: "Shefer", ar: "شيفِر" },
  "שקף": { en: "Sheqef", ar: "شيكِف" },
  "שריגים (לי-און)": { en: "Li-on", ar: "سَريچيم (لي أون)" },
  "שרשרת": { en: "Sharsheret", ar: "شَرشيرِت" },
  "תאשור": { en: "Te'ashur", ar: "تِأشور" },
  "תדהר": { en: "Tidhar", ar: "تِدهار" },
  "תושיה": { en: "Tushiyya", ar: "توشِيا" },
  "תל תאומים": { en: "Tel Te'omim", ar: "تيل تِؤوميم" },
  "תעוז": { en: "Ta'oz", ar: "تَعوز" },
  "תראבין א-צאנע (שבט)": { en: "Tarabin As-sani", ar: "ترابين الصانع" },
  "תראבין א-צאנע(ישוב)": { en: "Tarabin As-sani", ar: "ترابين الصانع" },
  "תרום": { en: "Tarum", ar: "تَروم" },
  // ── remaining DB localities (english from israel_cities.py) ──
  "מעלות תרשיחא": { en: "Ma'alot-Tarshiha" },
  "עפרה": { en: "Ofra" },
  // ── compound / alt-name localities (hand-mapped) ──
  "אדם - גבע בנימין": { en: "Adam (Geva Binyamin)" },
  "אזור תעשייה שער בנימין": { en: "Sha'ar Binyamin" },
  "אשדות יעקב מאוחד": { en: "Ashdot Ya'akov Meuhad" },
  "בית אריה / עופרים": { en: "Beit Arye-Ofarim" },
  "דאלית אל כרמל": { en: "Daliyat al-Karmel" },
  "הודייה": { en: "Hodaya" },
  "חד נס": { en: "Had Nes" },
  "חירן": { en: "Hiran" },
  "חפצי בה": { en: "Hefzi-Bah" },
  "ים המלח בתי מלון": { en: "Dead Sea Hotels" },
  "כוכב יאיר צור יגאל": { en: "Kochav Yair-Tzur Yigal" },
  "כינרת מושבה": { en: "Kinneret (Moshava)" },
  "כפר אלדד": { en: "Kfar Eldad" },
  "מיתר / כרמית": { en: "Meitar" },
  "מצדות יהודה / בית יתיר": { en: "Metzadot Yehuda-Beit Yatir" },
  "נווה צוף - חלמיש": { en: "Neve Tzuf (Halamish)" },
  "נעמי": { en: "Naomi" },
  "נצרת עילית / נוף הגליל": { en: "Nof HaGalil" },
  "עין זיתים": { en: "Ein Zeitim" },
  "רם און": { en: "Ram-On" },
  "שני ליבנה": { en: "Shani-Livne" },
  // ── OnMap Latin-merge targets ──
  "כרמית": { en: "Carmit" },
  "גאה": { en: "Ge'a" },
}

/**
 * Translate a Hebrew city name to the given language.
 * Falls back: requested language → English → original Hebrew.
 */
// ── Hebrew → Latin transliteration (fallback) ────────────────────────────────
// Used only when a city has no curated translation, so non-Hebrew UIs never
// show Hebrew script (the long tail of small localities). Approximate but
// readable Latin — curated names in CITY_TRANSLATIONS always take precedence.
const HEB_TO_LAT: Record<string, string> = {
  'א': 'a', 'ב': 'b', 'ג': 'g', 'ד': 'd', 'ה': 'h', 'ו': 'v', 'ז': 'z',
  'ח': 'ch', 'ט': 't', 'י': 'y', 'כ': 'k', 'ך': 'k', 'ל': 'l', 'מ': 'm',
  'ם': 'm', 'נ': 'n', 'ן': 'n', 'ס': 's', 'ע': 'a', 'פ': 'p', 'ף': 'f',
  'צ': 'tz', 'ץ': 'tz', 'ק': 'k', 'ר': 'r', 'ש': 'sh', 'ת': 't',
}
export function transliterateHebrew(s: string): string {
  return s
    .replace(/["'’‘״׳`().]/g, '')
    .split(/\s+/)
    .filter(Boolean)
    .map(word => {
      let out = ''
      for (const ch of word) {
        out += HEB_TO_LAT[ch] ?? (/[A-Za-z0-9-]/.test(ch) ? ch : '')
      }
      return out ? out[0].toUpperCase() + out.slice(1) : ''
    })
    .filter(Boolean)
    .join(' ')
    .trim()
}

export function translateCity(hebrewName: string | null | undefined, lang: string): string {
  if (!hebrewName) return ''
  if (lang === 'he') return hebrewName
  // Normalize whitespace (collapses double-spaces common in DB exports)
  const normalized = hebrewName.replace(/\s+/g, ' ').trim()
  const entry = CITY_TRANSLATIONS[normalized] ?? CITY_TRANSLATIONS[hebrewName]
  const isHeb = /[֐-׿]/.test(normalized)
  // No curated translation → transliterate Hebrew so non-Hebrew UIs never show
  // Hebrew script. If the name is already Latin (some OnMap strings), keep it.
  if (!entry) return isHeb ? transliterateHebrew(normalized) : normalized
  return entry[lang] ?? entry['en'] ?? (isHeb ? transliterateHebrew(normalized) : normalized)
}

/** Returns true if the string contains Hebrew characters. */
export function containsHebrew(s: string | null | undefined): boolean {
  return !!s?.match(/[֐-׿]/)
}

/**
 * Build a location string from street / neighborhood / city.
 * In non-Hebrew languages, Hebrew-script fields (street, neighborhood)
 * are skipped so we never show mixed-script addresses.
 */
export function buildAddress(
  street: string | null | undefined,
  neighborhood: string | null | undefined,
  city: string | null | undefined,
  lang: string,
): string {
  const cityDisplay = translateCity(city, lang)
  if (lang === 'he') {
    return [street, neighborhood, cityDisplay].filter(Boolean).join(', ')
  }
  return [
    !containsHebrew(street)       ? street       : null,
    !containsHebrew(neighborhood) ? neighborhood : null,
    cityDisplay,
  ].filter(Boolean).join(', ')
}
