/**
 * Blog - index of all weekly market reports + ad-hoc articles.
 *
 * Content lives in /public/blog as markdown files; the index is in
 * /public/blog/index.json, generated by scripts/generate_weekly_report.py.
 *
 * Why we built this:
 *   Substantive content = ranks for informational queries.
 *   ("Tel Aviv real estate market 2026", "Jerusalem rent trends", etc.)
 *   Weekly posts compound - every new week is one more indexable article
 *   that drives organic traffic from people researching the market.
 */
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useSeo } from '../hooks/useSeo'

interface Post {
  slug:     string
  date:     string
  title:    string
  titleHe?: string
  excerpt?: string
}

export default function Blog() {
  const { t, i18n } = useTranslation()
  const [posts, setPosts] = useState<Post[]>([])
  const [loading, setLoading] = useState(true)
  const isHebrew = i18n.language === 'he'
  const dateLocale =
    i18n.language === 'he' ? 'he-IL' :
    i18n.language === 'ru' ? 'ru-RU' :
    i18n.language === 'ar' ? 'ar'    :
    i18n.language === 'fr' ? 'fr-FR' : 'en-US'

  useSeo({
    title: t('blog.seoTitle'),
    description: t('blog.seoDescription'),
    url: 'https://www.bebkey.com/blog',
  })

  useEffect(() => {
    fetch('/blog/index.json')
      .then(r => r.ok ? r.json() : [])
      .then((data: Post[]) => setPosts(Array.isArray(data) ? data : []))
      .catch(() => setPosts([]))
      .finally(() => setLoading(false))
  }, [])

  return (
    <div className="max-w-3xl mx-auto px-4 py-10 sm:py-14">
      <h1 className="text-3xl sm:text-4xl font-bold text-gray-800 mb-3">
        {t('blog.title')}
      </h1>
      <p className="text-gray-500 mb-10">
        {t('blog.subtitle')}
      </p>

      {loading ? (
        <div className="space-y-6">
          {[1, 2, 3].map(i => (
            <div key={i} className="bg-gray-100 h-28 rounded-2xl animate-pulse" />
          ))}
        </div>
      ) : posts.length === 0 ? (
        <p className="text-gray-500 text-sm">
          {t('blog.empty')}
        </p>
      ) : (
        <div className="space-y-6">
          {posts.map(p => (
            <Link
              key={p.slug}
              to={`/blog/${p.slug}`}
              className="block bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow p-6"
            >
              <p className="text-xs text-gray-400 uppercase tracking-wide mb-1">
                {new Date(p.date).toLocaleDateString(
                  dateLocale,
                  { year: 'numeric', month: 'long', day: 'numeric' },
                )}
              </p>
              <h2 className="text-lg font-bold text-gray-800 mb-2">
                {isHebrew && p.titleHe ? p.titleHe : p.title}
              </h2>
              {p.excerpt && (
                <p className="text-sm text-gray-600 leading-relaxed">{p.excerpt}</p>
              )}
              <p className="text-sm text-brand-blue font-medium mt-3">
                {t('blog.read')} →
              </p>
            </Link>
          ))}
        </div>
      )}
    </div>
  )
}
